import { Chapter } from "@/lib/types";

// ============================================================
// 第 9 部分　容器与 Kubernetes（云原生核心，对标 CKA）
// 暂归入 tier 3（进阶地图重做后再对齐为 L5）
// ============================================================

export const PART9: Chapter[] = [
  // ---------------------- 9-1 ----------------------
  {
    id: "9-1",
    part: 9,
    index: "K1",
    title: "为什么需要容器",
    summary: "容器解决了什么问题、容器 vs 虚拟机、镜像/容器/仓库。",
    tier: 3,
    minutes: 22,
    objectives: ["理解容器解决的“环境不一致”痛点", "分清容器与虚拟机的区别", "理解镜像、容器、仓库三个核心概念"],
    blocks: [
      { type: "h2", text: "“在我电脑上明明能跑啊”" },
      { type: "p", text: "传统部署最大的痛点是**环境不一致**：开发机能跑，搬到服务器就因为系统版本、依赖库、配置不同而出错。**容器**就是来根治这件事的——把应用和它需要的一切（依赖、库、配置）**打包成一个标准盒子**，这个盒子在哪都一样地跑。" },
      { type: "h2", text: "容器 vs 虚拟机" },
      { type: "p", text: "虚拟机(VM)是在物理机上虚拟出**一整台带操作系统的电脑**，重；容器**共享宿主机的内核**，只打包应用层，轻得多、秒级启动。" },
      { type: "table", headers: ["维度", "虚拟机", "容器"], rows: [
        ["隔离粒度", "完整操作系统", "进程级，共享内核"],
        ["体积", "几个 GB", "几十~几百 MB"],
        ["启动速度", "几十秒~分钟", "秒级"],
        ["单机能跑多少", "几个", "几十上百个"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "容器为什么这么轻", body: "VM 要模拟硬件并各自装一套操作系统；容器则共用宿主机内核，只隔离出独立的文件系统、网络、进程空间。少了“每个都背一套 OS”的负担，所以又小又快。但隔离性弱于 VM，安全要求极高时仍会用 VM 或两者结合。" },
      { type: "h2", text: "三个核心概念：镜像 / 容器 / 仓库" },
      { type: "list", items: [
        "**镜像(Image)**：只读模板，打包好应用和环境（像“安装盘”或“类”）",
        "**容器(Container)**：镜像运行起来的实例（像“运行中的程序”或“对象”），可同时跑多个",
        "**仓库(Registry)**：存放和分发镜像的地方，如 Docker Hub、各云的镜像仓库",
      ] },
      { type: "callout", variant: "key", title: "一句话串起来", body: "从仓库**拉取(pull)** 镜像 → 用镜像**运行(run)** 出容器 → 应用就跑起来了。改好应用后**构建(build)** 成新镜像 → **推送(push)** 回仓库，别人就能用同一份。" },
      { type: "callout", variant: "tip", title: "🧪 动手练", body: "打开 killercoda 的 Docker 场景，敲 `docker run hello-world`，看它自动拉镜像、跑容器、打印信息——这就是“拉镜像→起容器”最小的一次完整体验。" },
    ],
    quiz: [
      { id: "9-1-q1", kind: "single", question: "容器主要解决了什么核心痛点？", options: ["让电脑更快", "环境不一致（开发能跑、上线就崩）", "省电费", "替代数据库"], answer: [1], explanation: "容器把应用与依赖打包，保证“到哪都一样地跑”，根治环境不一致。" },
      { id: "9-1-q2", kind: "single", question: "容器相比虚拟机更轻的根本原因是？", options: ["不需要应用", "共享宿主机内核，不各自带一套操作系统", "用了更好的CPU", "不联网"], answer: [1], explanation: "容器共享内核、只隔离应用层，省去每个都装一套 OS 的开销。" },
      { id: "9-1-q3", kind: "single", question: "“镜像”和“容器”的关系最像？", options: ["完全相同", "安装盘(模板) 与 运行中的程序(实例)", "硬件与软件", "网线与网卡"], answer: [1], explanation: "镜像是只读模板，容器是镜像运行起来的实例，可同时跑多个。" },
      { id: "9-1-q4", kind: "single", question: "Docker Hub 属于？", options: ["容器", "镜像仓库(Registry)", "操作系统", "编程语言"], answer: [1], explanation: "Docker Hub 是公共镜像仓库，用于存放和分发镜像。" },
    ],
    flashcards: [
      { id: "9-1-f1", front: "容器解决什么问题", back: "环境不一致：把应用+依赖打包成标准盒子，到哪都一样地跑。", chapterId: "9-1" },
      { id: "9-1-f2", front: "容器 vs 虚拟机", back: "容器共享内核、轻、秒级、可跑很多；VM 带整套OS、重。", chapterId: "9-1" },
      { id: "9-1-f3", front: "镜像/容器/仓库", back: "镜像=只读模板；容器=运行实例；仓库=存分发镜像(Docker Hub)。", chapterId: "9-1" },
      { id: "9-1-f4", front: "核心动作", back: "pull 拉镜像 → run 起容器 → build 构建新镜像 → push 推回仓库。", chapterId: "9-1" },
    ],
  },

  // ---------------------- 9-2 ----------------------
  {
    id: "9-2",
    part: 9,
    index: "K2",
    title: "Docker 上手",
    summary: "最常用的 docker 命令、端口与数据卷、用 Dockerfile 构建镜像。",
    tier: 3,
    minutes: 26,
    objectives: ["熟练用 docker run/ps/logs/exec 操作容器", "理解端口映射与数据卷", "看懂并写出最简单的 Dockerfile"],
    blocks: [
      { type: "h2", text: "最常用的 Docker 命令" },
      { type: "table", headers: ["命令", "作用"], rows: [
        ["docker run -d -p 8080:80 nginx", "后台跑 nginx，把宿主 8080 映射到容器 80"],
        ["docker ps（-a）", "看运行中的容器（-a 含已停止）"],
        ["docker images", "看本地镜像"],
        ["docker logs 容器", "看容器日志"],
        ["docker exec -it 容器 bash", "进入容器内部终端"],
        ["docker stop / rm 容器", "停止 / 删除容器"],
        ["docker pull / push 镜像", "拉取 / 推送镜像"],
      ] },
      { type: "knowledge", discipline: "通信", title: "端口映射 -p 宿主:容器", body: "容器有自己独立的网络，外部默认访问不到。`-p 8080:80` 表示把宿主机的 8080 端口转发到容器的 80 端口，于是浏览器访问 宿主IP:8080 就能到达容器里的服务。冒号左边是宿主、右边是容器，别记反。" },
      { type: "h2", text: "数据卷：让数据不随容器消失" },
      { type: "p", text: "容器删了，里面的数据也没了。要持久化（比如数据库文件），用**数据卷**把宿主目录挂进容器：`-v 宿主路径:容器路径`。这样数据存在宿主上，容器重建也不丢。" },
      { type: "h2", text: "用 Dockerfile 构建自己的镜像" },
      { type: "p", text: "**Dockerfile** 是构建镜像的“配方”，逐行声明怎么把应用打包成镜像。最小例子：" },
      { type: "list", items: [
        "`FROM node:20` —— 以某基础镜像起步",
        "`WORKDIR /app` —— 设定工作目录",
        "`COPY . .` —— 把代码拷进镜像",
        "`RUN npm install` —— 构建时执行（装依赖）",
        "`CMD [\"node\", \"app.js\"]` —— 容器启动时运行的命令",
      ] },
      { type: "list", ordered: true, items: [
        "写好 Dockerfile 后：`docker build -t myapp:1.0 .` 构建镜像",
        "`docker run -d -p 3000:3000 myapp:1.0` 运行它",
      ] },
      { type: "callout", variant: "info", title: "RUN vs CMD", body: "`RUN` 在**构建镜像时**执行（如装依赖），结果固化进镜像；`CMD` 是**容器启动时**默认运行的命令。一个 Dockerfile 可多个 RUN，但通常只一个 CMD。" },
      { type: "callout", variant: "tip", title: "🧪 动手练", body: "killercoda Docker：`docker run -d -p 8080:80 nginx` → `docker ps` 看它在跑 → `curl localhost:8080` 看到 nginx 页面 → `docker exec -it 容器ID sh` 进去转一圈 → `docker logs 容器ID` 看日志。" },
    ],
    quiz: [
      { id: "9-2-q1", kind: "single", question: "`-p 8080:80` 的含义是？", options: ["容器8080映射到宿主80", "宿主8080映射到容器80", "开放两个端口", "限制带宽"], answer: [1], explanation: "冒号左边宿主、右边容器：宿主 8080 → 容器 80。" },
      { id: "9-2-q2", kind: "single", question: "想让容器删除后数据还在，应该用？", options: ["docker logs", "数据卷 -v 宿主:容器", "docker ps -a", "多开几个容器"], answer: [1], explanation: "用 -v 把宿主目录挂载进容器，数据存宿主上，容器重建不丢。" },
      { id: "9-2-q3", kind: "single", question: "Dockerfile 中容器启动时默认运行的命令用哪个指令？", options: ["FROM", "RUN", "CMD", "COPY"], answer: [2], explanation: "CMD 指定容器启动时运行的默认命令；RUN 是构建镜像时执行。" },
      { id: "9-2-q4", kind: "single", question: "进入正在运行的容器内部终端用？", options: ["docker run", "docker exec -it 容器 bash", "docker build", "docker pull"], answer: [1], explanation: "docker exec -it 容器 bash/sh 进入容器交互终端，常用于排查。" },
    ],
    flashcards: [
      { id: "9-2-f1", front: "docker run 常用参数", back: "-d 后台、-p 宿主:容器 端口映射、-v 宿主:容器 挂卷、-it 交互。", chapterId: "9-2" },
      { id: "9-2-f2", front: "端口映射方向", back: "-p 左宿主:右容器；浏览器访问 宿主IP:宿主端口 到达容器。", chapterId: "9-2" },
      { id: "9-2-f3", front: "Dockerfile 关键指令", back: "FROM 基础镜像、COPY 拷代码、RUN 构建时执行、CMD 启动时运行。", chapterId: "9-2" },
      { id: "9-2-f4", front: "构建并运行镜像", back: "docker build -t 名:版本 . → docker run -d -p ... 名:版本。", chapterId: "9-2" },
    ],
  },

  // ---------------------- 9-3 ----------------------
  {
    id: "9-3",
    part: 9,
    index: "K3",
    title: "为什么需要 Kubernetes",
    summary: "容器编排要解决什么、声明式与自愈、K8s 架构总览。",
    tier: 3,
    minutes: 24,
    objectives: ["理解为何需要容器编排", "理解声明式与自愈的思想", "认识 K8s 控制平面与工作节点的组成"],
    blocks: [
      { type: "h2", text: "几百个容器，谁来管？" },
      { type: "p", text: "单机跑几个容器，Docker 够用。可一旦上了规模——几十台机器、成百上千容器——问题来了：谁负责把容器**调度**到合适的机器？某个容器挂了谁**自动拉起**？流量大了怎么**自动扩容**？怎么**滚动更新**不中断？这些“编排”工作，就是 **Kubernetes(K8s)** 干的。" },
      { type: "knowledge", discipline: "计算机", title: "声明式 vs 命令式（K8s 的灵魂）", body: "命令式是你一步步下指令（“启动这个、再启动那个”）；声明式是你描述**期望的最终状态**（“我要 3 个副本一直在线”），K8s 自己想办法达成并持续维持。节点宕了它自动在别处补上——这就是**自愈**。理解这一点，就理解了 K8s 的核心思维。" },
      { type: "h2", text: "K8s 能为你做什么" },
      { type: "list", items: [
        "**自愈**：容器/节点挂了自动重建，维持期望副本数",
        "**弹性伸缩**：按负载自动增减副本",
        "**滚动更新/回滚**：不停机升级，出问题一键回退",
        "**服务发现与负载均衡**：自动把流量分到健康的副本",
        "**配置与密钥管理、存储编排**：统一管理",
      ] },
      { type: "h2", text: "K8s 架构总览" },
      { type: "p", text: "一个 K8s 集群 = **控制平面(大脑)** + 若干 **工作节点(干活的)**。" },
      { type: "table", headers: ["组件", "在哪", "作用"], rows: [
        ["API Server", "控制平面", "集群的统一入口，所有操作都经过它"],
        ["etcd", "控制平面", "键值数据库，存集群的全部状态"],
        ["Scheduler", "控制平面", "决定 Pod 调度到哪个节点"],
        ["Controller Manager", "控制平面", "持续把实际状态拉向期望状态(自愈)"],
        ["kubelet", "工作节点", "在节点上干活，管理本机容器"],
        ["kube-proxy", "工作节点", "负责网络与转发"],
        ["容器运行时", "工作节点", "真正跑容器(如 containerd)"],
      ] },
      { type: "callout", variant: "key", title: "你只跟 API Server 打交道", body: "你用 `kubectl` 提交“我要什么”给 API Server，状态存进 etcd，各控制器和节点上的 kubelet 协作把它变成现实。你管“想要什么”，K8s 管“怎么实现+一直维持”。" },
      { type: "callout", variant: "info", title: "k3s 是什么", body: "你 homelab 装的 **k3s** 是轻量级 K8s，把这些组件打包得很小、单命令安装，特别适合学习和资源有限的环境。概念与标准 K8s 完全一致，命令也通用。" },
    ],
    quiz: [
      { id: "9-3-q1", kind: "single", question: "Kubernetes 主要解决什么？", options: ["写代码", "大规模容器的编排(调度/自愈/扩缩/更新)", "替代 Linux", "做网页"], answer: [1], explanation: "K8s 负责把大量容器在集群里自动调度、自愈、伸缩、滚动更新。" },
      { id: "9-3-q2", kind: "single", question: "“声明式”指的是？", options: ["一步步下命令", "描述期望状态，由系统自动达成并维持", "只读不写", "手动重启"], answer: [1], explanation: "你声明想要的最终状态，K8s 持续把实际状态拉向它，实现自愈。" },
      { id: "9-3-q3", kind: "single", question: "集群的统一入口、所有操作都经过的组件是？", options: ["etcd", "API Server", "kubelet", "kube-proxy"], answer: [1], explanation: "API Server 是集群入口；etcd 存状态；kubelet 在节点上干活。" },
      { id: "9-3-q4", kind: "single", question: "存储整个集群状态的键值数据库是？", options: ["MySQL", "etcd", "Redis", "kubelet"], answer: [1], explanation: "etcd 是 K8s 的状态存储，保存集群全部期望与实际状态。" },
    ],
    flashcards: [
      { id: "9-3-f1", front: "为何需要 K8s", back: "大规模容器的编排：自动调度、自愈、弹性伸缩、滚动更新、服务发现。", chapterId: "9-3" },
      { id: "9-3-f2", front: "声明式 + 自愈", back: "你声明期望状态，K8s 持续维持；节点挂了自动在别处补。", chapterId: "9-3" },
      { id: "9-3-f3", front: "控制平面四件", back: "API Server(入口)、etcd(状态库)、Scheduler(调度)、Controller(自愈)。", chapterId: "9-3" },
      { id: "9-3-f4", front: "工作节点三件 + k3s", back: "kubelet、kube-proxy、容器运行时；k3s 是轻量 K8s，概念命令通用。", chapterId: "9-3" },
    ],
  },

  // ---------------------- 9-4 ----------------------
  {
    id: "9-4",
    part: 9,
    index: "K4",
    title: "Kubernetes 核心对象",
    summary: "Pod、Deployment、Service、Namespace 与 YAML 声明式部署。",
    tier: 3,
    minutes: 28,
    objectives: ["理解 Pod/Deployment/Service/Namespace 的职责", "看懂并写出基础 YAML", "用 kubectl apply 声明式部署"],
    blocks: [
      { type: "h2", text: "四个你天天打交道的对象" },
      { type: "table", headers: ["对象", "是什么", "一句话"], rows: [
        ["Pod", "最小调度单位", "包 1 个(或多个)容器，K8s 调度的基本单元"],
        ["Deployment", "管理一组 Pod", "维持副本数、滚动更新、自愈，最常用"],
        ["Service", "稳定的访问入口", "给一组会变的 Pod 提供固定地址 + 负载均衡"],
        ["Namespace", "逻辑隔离", "把对象分组(如 dev/prod)，互不干扰"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "为什么不直接用 Pod，而用 Deployment", body: "Pod 是“一次性”的——挂了不会自己回来，IP 还会变。Deployment 在 Pod 之上管理副本：声明“我要 3 个”，挂了它补、升级时滚动替换、可一键回滚。所以生产里你几乎总是创建 Deployment，而不是裸 Pod。" },
      { type: "knowledge", discipline: "通信", title: "Service 怎么找到该转发给哪些 Pod", body: "靠**标签(label)与选择器(selector)**：Pod 打上标签 app=web，Service 的 selector 写 app=web，就自动把流量分发到所有带这个标签的健康 Pod。Pod 重建后 IP 变了也没关系，Service 这个固定入口始终有效。" },
      { type: "h2", text: "声明式 YAML + kubectl apply" },
      { type: "p", text: "你把“想要什么”写进 **YAML** 文件，用 `kubectl apply -f 文件.yaml` 提交给集群。一个最简 Deployment 的关键字段：" },
      { type: "list", items: [
        "`kind: Deployment` —— 对象类型",
        "`spec.replicas: 3` —— 我要 3 个副本",
        "`spec.selector` / `template.metadata.labels` —— 用标签把 Deployment 和它管的 Pod 关联",
        "`template.spec.containers` —— Pod 里跑什么镜像、开什么端口",
      ] },
      { type: "h2", text: "最常用的 kubectl 命令" },
      { type: "list", items: [
        "`kubectl apply -f x.yaml` 声明式创建/更新",
        "`kubectl get pods/de1/svc`（加 `-A` 看所有命名空间）",
        "`kubectl describe pod 名` 看详情与事件",
        "`kubectl scale deployment web --replicas=5` 扩缩容",
        "`kubectl delete -f x.yaml` 删除",
      ] },
      { type: "callout", variant: "tip", title: "🧪 动手练（在你的 homelab k3s 上）", body: "命令式快速体验：`kubectl create deployment web --image=nginx` → `kubectl scale deployment web --replicas=3` → `kubectl get pods`（看到 3 个）→ 删掉一个 Pod `kubectl delete pod <名>` → 再 get pods，观察它**自动补回**第 3 个，亲眼见证自愈。" },
    ],
    quiz: [
      { id: "9-4-q1", kind: "single", question: "K8s 中最小的调度单位是？", options: ["容器", "Pod", "Deployment", "Node"], answer: [1], explanation: "Pod 是最小调度单位，内含一个或多个共享网络/存储的容器。" },
      { id: "9-4-q2", kind: "single", question: "为什么生产中常用 Deployment 而非裸 Pod？", options: ["Pod 收费", "Deployment 维持副本数、滚动更新、自愈", "Pod 不能跑容器", "没区别"], answer: [1], explanation: "Deployment 管理副本，提供自愈、滚动更新与回滚能力。" },
      { id: "9-4-q3", kind: "single", question: "Service 靠什么决定把流量转发给哪些 Pod？", options: ["Pod 的 IP", "标签(label)与选择器(selector)", "Pod 名字顺序", "节点编号"], answer: [1], explanation: "Service 通过 selector 匹配 Pod 的 label，自动负载均衡到这些 Pod。" },
      { id: "9-4-q4", kind: "single", question: "声明式部署一个 YAML 用哪条命令？", options: ["kubectl run", "kubectl apply -f 文件", "docker build", "kubectl logs"], answer: [1], explanation: "kubectl apply -f 文件.yaml 按声明的期望状态创建/更新对象。" },
    ],
    flashcards: [
      { id: "9-4-f1", front: "四大核心对象", back: "Pod(最小单位)、Deployment(管副本/自愈)、Service(固定入口/负载均衡)、Namespace(隔离)。", chapterId: "9-4" },
      { id: "9-4-f2", front: "Pod vs Deployment", back: "裸 Pod 挂了不自愈、IP会变；Deployment 维持副本、滚动更新、可回滚。", chapterId: "9-4" },
      { id: "9-4-f3", front: "Service 如何找 Pod", back: "靠 label/selector 匹配，自动负载均衡到带该标签的健康 Pod。", chapterId: "9-4" },
      { id: "9-4-f4", front: "声明式部署", back: "写 YAML → kubectl apply -f；get/describe/scale/delete 管理。", chapterId: "9-4" },
    ],
  },

  // ---------------------- 9-5 ----------------------
  {
    id: "9-5",
    part: 9,
    index: "K5",
    title: "配置、存储与网络",
    summary: "ConfigMap/Secret、持久化存储、Service 类型与 Ingress。",
    tier: 3,
    minutes: 26,
    objectives: ["用 ConfigMap/Secret 管理配置与密钥", "理解持久化存储 PV/PVC", "分清 Service 类型与 Ingress 的作用"],
    blocks: [
      { type: "h2", text: "配置与密钥：别把它们写死在镜像里" },
      { type: "list", items: [
        "**ConfigMap**：存非敏感配置（如环境变量、配置文件），与镜像解耦，改配置不用重建镜像",
        "**Secret**：存敏感信息（密码、密钥、证书），用法类似 ConfigMap 但更注意保护",
      ] },
      { type: "callout", variant: "key", title: "为什么要解耦配置", body: "同一个镜像要在开发/测试/生产跑，差异(数据库地址、密码)应来自 ConfigMap/Secret，而不是打进镜像。这样“一次构建，到处运行”，也更安全。" },
      { type: "h2", text: "持久化存储：PV 与 PVC" },
      { type: "p", text: "Pod 重建后本地数据会丢。要持久化（数据库等），用存储卷：" },
      { type: "list", items: [
        "**PV(PersistentVolume)**：集群里一块实际的存储资源（管理员/存储系统提供）",
        "**PVC(PersistentVolumeClaim)**：应用提出的“我要一块多大的存储”的申领，K8s 把它绑定到合适的 PV",
        "Pod 挂载 PVC，数据就独立于 Pod 生命周期，重建不丢",
      ] },
      { type: "knowledge", discipline: "计算机", title: "PV/PVC 像“宿舍与住宿申请”", body: "PV 是已经盖好的宿舍（实际存储），PVC 是你提交的住宿申请（要多大、什么权限），系统按申请把你分到合适的宿舍。应用只管提 PVC，不用关心底层存储是云盘还是 NFS——这就是“存储编排”的解耦之美。" },
      { type: "h2", text: "网络：Service 类型与 Ingress" },
      { type: "table", headers: ["类型", "作用", "适用"], rows: [
        ["ClusterIP", "集群内部访问(默认)", "服务间互调"],
        ["NodePort", "通过 节点IP:端口 暴露到外部", "测试/homelab 对外"],
        ["LoadBalancer", "云负载均衡器对外", "云上生产对外"],
        ["Ingress", "七层(HTTP)路由，按域名/路径分发", "用一个入口暴露多个服务"],
      ] },
      { type: "callout", variant: "info", title: "Ingress 解决什么", body: "NodePort/LoadBalancer 一个服务一个入口，多了很乱也费资源。Ingress 是统一的 HTTP 入口，按**域名/路径**把请求路由到不同 Service（如 a.com→服务A、b.com→服务B），还能统一管 HTTPS 证书。" },
      { type: "callout", variant: "tip", title: "🧪 动手练", body: "在 homelab k3s：把上一章的 web 用 NodePort 暴露 `kubectl expose deployment web --port=80 --type=NodePort` → `kubectl get svc` 看端口 → 浏览器 `http://联想IP:端口` 访问。再试创建一个 ConfigMap 注入环境变量，体会配置解耦。" },
    ],
    quiz: [
      { id: "9-5-q1", kind: "single", question: "存放数据库密码这类敏感信息应该用？", options: ["ConfigMap", "Secret", "直接写进镜像", "写在 Pod 名里"], answer: [1], explanation: "Secret 用于敏感信息；ConfigMap 用于非敏感配置；都不应写死进镜像。" },
      { id: "9-5-q2", kind: "single", question: "应用申领持久化存储用的是？", options: ["PV", "PVC", "Pod", "Service"], answer: [1], explanation: "PVC 是应用对存储的申领，K8s 将其绑定到实际的 PV。" },
      { id: "9-5-q3", kind: "single", question: "默认、仅集群内部可访问的 Service 类型是？", options: ["ClusterIP", "NodePort", "LoadBalancer", "Ingress"], answer: [0], explanation: "ClusterIP 是默认类型，只在集群内部可达。" },
      { id: "9-5-q4", kind: "single", question: "想用一个入口按域名/路径把流量分发到多个服务，用？", options: ["NodePort", "Ingress", "ConfigMap", "PVC"], answer: [1], explanation: "Ingress 提供七层 HTTP 路由，按域名/路径分发并可统一管理 HTTPS。" },
    ],
    flashcards: [
      { id: "9-5-f1", front: "ConfigMap vs Secret", back: "ConfigMap 存非敏感配置；Secret 存密码/密钥；都与镜像解耦。", chapterId: "9-5" },
      { id: "9-5-f2", front: "PV / PVC", back: "PV=实际存储；PVC=应用的存储申领；Pod 挂 PVC，数据不随 Pod 丢。", chapterId: "9-5" },
      { id: "9-5-f3", front: "Service 三类型", back: "ClusterIP(内部)、NodePort(节点IP:端口对外)、LoadBalancer(云LB)。", chapterId: "9-5" },
      { id: "9-5-f4", front: "Ingress", back: "统一 HTTP 入口，按域名/路径路由到多个 Service，统管 HTTPS。", chapterId: "9-5" },
    ],
  },

  // ---------------------- 9-6 ----------------------
  {
    id: "9-6",
    part: 9,
    index: "K6",
    title: "排障与实战（对标 CKA）",
    summary: "Pod 常见异常、排障命令、homelab 完整部署与 CKA 备考。",
    tier: 3,
    minutes: 32,
    objectives: ["掌握 K8s 排障命令与套路", "认识常见 Pod 异常状态及原因", "在 homelab 完成一次完整部署，了解 CKA 备考"],
    blocks: [
      { type: "h2", text: "排障四件套" },
      { type: "list", items: [
        "`kubectl get pods` 看状态（哪个不正常）",
        "`kubectl describe pod 名` 看详情和底部 **Events**（最关键，原因常在这）",
        "`kubectl logs 名`（`-f` 实时，`--previous` 看崩溃前的）看应用日志",
        "`kubectl exec -it 名 -- sh` 进容器里手动验证",
      ] },
      { type: "h2", text: "常见 Pod 异常状态" },
      { type: "table", headers: ["状态", "含义", "常见原因/排查"], rows: [
        ["Pending", "调度不上去", "节点资源不足 / 没有满足条件的节点 / PVC 未绑定"],
        ["ImagePullBackOff", "拉不到镜像", "镜像名/标签写错、私有仓库没认证、网络不通"],
        ["CrashLoopBackOff", "起来就崩、反复重启", "应用本身报错 → 看 logs；配置/依赖缺失"],
        ["Running 但不可用", "在跑但服务异常", "看 logs、检查就绪探针、Service/selector 是否匹配"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "排障的通用心法", body: "和前面故障排查情景里一样：**先观察(get)→看细节与事件(describe)→看日志(logs)→进去验证(exec)**，自顶向下、用证据说话。describe 的 Events 和 logs 是 90% 问题的答案所在。" },
      { type: "h2", text: "实战：在 homelab 完整部署一个应用" },
      { type: "list", ordered: true, items: [
        "写 `web.yaml`：一个 Deployment(nginx, replicas:2) + 一个 NodePort Service，用同一组 label 关联",
        "`kubectl apply -f web.yaml` 部署",
        "`kubectl get pods,svc` 确认 2 个 Pod Running、Service 拿到 NodePort",
        "浏览器 `http://联想IP:NodePort` 访问成功",
        "`kubectl scale deployment web --replicas=4` 扩容，再 get pods 观察",
        "删掉一个 Pod，观察自愈补回；改 image 版本 apply，观察滚动更新",
      ] },
      { type: "callout", variant: "key", title: "🎯 CKA 备考提示", body: "CKA 是**纯上机实操考**：真集群里 2 小时做 15–20 道操作题，允许查 kubernetes.io 官方文档。所以备考核心就是**反复动手**：在 killercoda/kind/你的 homelab 上把创建、排障、扩缩、配置、存储练到形成肌肉记忆，并练熟用官方文档快速查 YAML 模板。" },
      { type: "callout", variant: "tip", title: "🧪 持续练", body: "把本部分每章的 🧪 实验都在 homelab 真做一遍；遇到不懂的报错，记进错题本式清单，到「今日训练」里循环攻克。命令不熟就去「实操练习 → 命令行模拟题」的 Kubernetes 分类刷。" },
    ],
    quiz: [
      { id: "9-6-q1", kind: "single", question: "排查 Pod 问题，最该先看哪里找原因？", options: ["重启电脑", "kubectl describe pod 的 Events 和 kubectl logs", "删了重建", "改名字"], answer: [1], explanation: "describe 的 Events 与 logs 是绝大多数问题的答案所在，先观察再动手。" },
      { id: "9-6-q2", kind: "single", question: "ImagePullBackOff 最可能的原因是？", options: ["应用代码崩溃", "拉不到镜像(名字错/未认证/网络)", "内存不足", "端口冲突"], answer: [1], explanation: "ImagePullBackOff 指拉取镜像失败，检查镜像名/标签、仓库认证、网络。" },
      { id: "9-6-q3", kind: "single", question: "CrashLoopBackOff 通常该怎么查？", options: ["看 kubectl logs 找应用报错", "重装系统", "加内存就行", "无解"], answer: [0], explanation: "CrashLoopBackOff 是应用起来就崩、反复重启，先看 logs 找崩溃原因。" },
      { id: "9-6-q4", kind: "single", question: "关于 CKA 考试，正确的是？", options: ["纯选择题", "上机实操、可查官方文档，重在动手", "只考理论", "不能用命令行"], answer: [1], explanation: "CKA 是真集群上机实操考，允许查 kubernetes.io 文档，核心是反复动手。" },
    ],
    flashcards: [
      { id: "9-6-f1", front: "K8s 排障四件套", back: "get(看状态)→describe(看Events)→logs(看日志)→exec(进去验证)。", chapterId: "9-6" },
      { id: "9-6-f2", front: "三大异常状态", back: "Pending(调度不上/资源)、ImagePullBackOff(拉镜像失败)、CrashLoopBackOff(应用崩)。", chapterId: "9-6" },
      { id: "9-6-f3", front: "自愈与滚动更新", back: "删Pod自动补回；改image后apply触发滚动更新，可回滚。", chapterId: "9-6" },
      { id: "9-6-f4", front: "CKA 怎么考/怎么备", back: "真集群上机实操、可查官方文档；靠在 killercoda/homelab 反复动手。", chapterId: "9-6" },
    ],
  },
];
