import { Chapter } from "@/lib/types";

export const PART6: Chapter[] = [
  // ---------------------- 第 28 章 ----------------------
  {
    id: "6-28",
    part: 6,
    index: "28",
    title: "可靠性与冗余设计",
    summary: "可用性、N/N+1/2N 冗余、单点故障与 MTBF/MTTR/SLA。",
    tier: 4,
    minutes: 26,
    objectives: [
      "理解可用性与“几个 9”",
      "掌握 N、N+1、2N 等冗余等级",
      "理解单点故障、MTBF/MTTR 与 SLA",
    ],
    blocks: [
      { type: "h2", text: "可用性：数据中心的命根子" },
      { type: "p", text: "数据中心卖的就是“不停机”。**可用性(Availability)** 用百分比衡量，业内常说“几个 9”——直接关系到一年允许宕机多久。" },
      { type: "widget", widget: "availability", title: "动手试试：可用性 / 宕机计算器" },
      { type: "knowledge", discipline: "数学", title: "可用性怎么算", body: "可用性 = MTBF ÷ (MTBF + MTTR)。MTBF=平均无故障时间(越长越好)，MTTR=平均修复时间(越短越好)。想提高可用性，要么让设备更耐用(MTBF↑)，要么坏了修得更快(MTTR↓)。" },
      { type: "h2", text: "单点故障(SPOF)：可靠性的敌人" },
      { type: "p", text: "**单点故障(Single Point of Failure)** 指某个部件一旦失效，整个系统就停。比如只有一路市电、一台 UPS、一根网线——它坏了全完。提高可靠性的核心思路就是：**找出 SPOF，用冗余消除它**。" },
      { type: "h2", text: "冗余等级：N / N+1 / 2N" },
      { type: "table", headers: ["等级", "含义", "举例(需2台够用)"], rows: [
        ["N", "刚好够用，无冗余", "2 台，坏1台就不够 ❌"],
        ["N+1", "多一台备份", "3 台，坏1台仍够 ✅"],
        ["N+2", "多两台备份", "4 台，可坏2台 ✅✅"],
        ["2N", "两套独立系统", "2+2，整套坏仍有另一套 ✅"],
        ["2N+1", "两套且各有备份", "最高级别冗余"],
      ] },
      { type: "callout", variant: "key", title: "N+1 与 2N 的区别", body: "N+1 是“多备一台部件”，省钱但共用同一套母线/路径仍可能有公共故障点；2N 是“两套完全独立的系统”，连路径都分开，可靠性最高、成本也最高。服务器双路供电(A/B)就是 2N 思想。" },
      { type: "widget", widget: "redundancy", title: "动手试试：N+1 / 2N 冗余推演" },
      { type: "h2", text: "SLA：白纸黑字的承诺" },
      { type: "p", text: "**SLA(服务等级协议)** 是服务商对客户承诺的服务质量指标，最核心的就是可用性（如承诺 99.99%）。达不到要赔偿。SLA 倒逼数据中心在设计和运维上保证可靠性。" },
      { type: "callout", variant: "info", title: "可靠性是“设计+运维”共同的结果", body: "再好的冗余设计，如果运维操作失误(误操作是宕机主因之一)也会出事。所以下一章的等级体系既看硬件冗余，也看“可维护性”，第 31 章则专讲运维流程。" },
    ],
    quiz: [
      { id: "6-28-q1", kind: "single", question: "可用性的计算式是？",
        options: ["MTTR ÷ MTBF", "MTBF ÷ (MTBF + MTTR)", "MTBF × MTTR", "1 ÷ MTBF"], answer: [1],
        explanation: "可用性=MTBF/(MTBF+MTTR)，设备越耐用、修得越快越高。" },
      { id: "6-28-q2", kind: "single", question: "2N 冗余相比 N+1 的关键区别是？",
        options: ["更便宜", "两套完全独立的系统(含路径)，可靠性最高", "只多一个部件", "没有区别"], answer: [1],
        explanation: "2N 是两套独立系统、路径也分开；N+1 仅多备一台部件。" },
      { id: "6-28-q3", kind: "single", question: "消除单点故障(SPOF)的核心手段是？",
        options: ["降低成本", "冗余(备份关键部件/路径)", "提高电压", "减少设备"], answer: [1],
        explanation: "用冗余为关键环节提供备份，避免单点失效导致全停。" },
      { id: "6-28-q4", kind: "single", question: "SLA 最核心的承诺指标通常是？",
        options: ["设备颜色", "可用性(如99.99%)", "员工人数", "机柜数量"], answer: [1],
        explanation: "SLA 核心是可用性承诺，达不到需赔偿。" },
    ],
    flashcards: [
      { id: "6-28-f1", front: "可用性公式", back: "可用性=MTBF/(MTBF+MTTR)。", chapterId: "6-28" },
      { id: "6-28-f2", front: "N/N+1/2N", back: "N刚好够;N+1多备一台;2N两套独立系统(最可靠)。", chapterId: "6-28" },
      { id: "6-28-f3", front: "SPOF", back: "单点故障：某部件失效则全停；用冗余消除。", chapterId: "6-28" },
      { id: "6-28-f4", front: "SLA", back: "服务等级协议，核心是可用性承诺，违约赔偿。", chapterId: "6-28" },
    ],
  },

  // ---------------------- 第 29 章 ----------------------
  {
    id: "6-29",
    part: 6,
    index: "29",
    title: "可用性等级体系",
    summary: "Uptime Tier I–IV 与 TIA-942 分级。",
    tier: 4,
    minutes: 22,
    objectives: [
      "掌握 Uptime Tier I–IV 的核心区别",
      "理解“可并行维护”与“容错”",
      "了解 TIA-942 与国标分级",
    ],
    blocks: [
      { type: "h2", text: "为什么需要等级" },
      { type: "p", text: "客户怎么知道一座数据中心有多可靠？靠**统一的等级标准**。最权威的是 **Uptime Institute 的 Tier 体系**（也是本站对标认证 CDCP 的重点）。" },
      { type: "h2", text: "Uptime Tier I–IV" },
      { type: "table", headers: ["等级", "核心特征", "通俗理解"], rows: [
        ["Tier I 基础型", "无冗余，单路径", "有 UPS/柴发，但维护/故障会停机"],
        ["Tier II 冗余组件", "关键部件 N+1 冗余", "部件有备份，但路径仍单一"],
        ["Tier III 可并行维护", "多路径(一用一备)，可在线维护", "任何部件可维护而不停业务"],
        ["Tier IV 容错", "完全 2N、容错", "任何单一故障都不影响运行"],
      ] },
      { type: "callout", variant: "key", title: "两个关键概念", body: "**可并行维护(Concurrently Maintainable, Tier III)**：任一部件都能停下来维护而业务不中断。**容错(Fault Tolerant, Tier IV)**：任一处突发故障都不影响运行。等级越高，冗余和独立路径要求越严，造价也越高。" },
      { type: "knowledge", discipline: "英语", title: "Tier 的认证种类", body: "Uptime 的 Tier 认证分：设计文件认证(Tier Certification of Design Documents)、已建设施认证(Constructed Facility)、运营可持续性(Operational Sustainability)。一座数据中心宣称 “Tier III”，要看它是“设计达标”还是“实建认证”。" },
      { type: "h2", text: "选哪个等级" },
      { type: "p", text: "不是越高越好，而是**匹配业务需求**：一般企业 Tier II–III 够用；金融、核心云等关键业务才上 Tier IV。等级越高越贵，要权衡可靠性与成本。" },
      { type: "h2", text: "其它标准" },
      { type: "list", items: [
        "**TIA-942**：电信行业的数据中心标准，含类似的 Rated 1–4 分级，还覆盖布线、选址、安防等；",
        "**国标 GB 50174**《数据中心设计规范》：国内把机房分为 **A、B、C 三级**（A 级最高），是国内设计建设的法定依据。",
      ] },
      { type: "callout", variant: "tip", title: "考点提醒", body: "Tier I–IV 的区别、“可并行维护 vs 容错”、国标 A/B/C 分级，是设施类认证(CDCP 等)的高频考点，务必记牢上表。" },
    ],
    quiz: [
      { id: "6-29-q1", kind: "single", question: "Uptime Tier III 的核心特征是？",
        options: ["无冗余", "关键部件N+1但单路径", "可并行维护(在线维护不停业务)", "完全容错"], answer: [2],
        explanation: "Tier III 多路径、可并行维护：任一部件可维护而不中断业务。" },
      { id: "6-29-q2", kind: "single", question: "Tier IV 相比 Tier III 增加了？",
        options: ["更便宜", "容错：任一突发单一故障都不影响运行", "取消冗余", "只是文件不同"], answer: [1],
        explanation: "Tier IV 在可并行维护之上还要容错，应对突发单一故障。" },
      { id: "6-29-q3", kind: "single", question: "国标 GB 50174 把数据中心分为？",
        options: ["Tier I-IV", "A、B、C 三级(A最高)", "1-10级", "甲乙丙丁"], answer: [1],
        explanation: "GB 50174 分 A/B/C 三级，A 级要求最高。" },
      { id: "6-29-q4", kind: "single", question: "关于选择等级，正确的说法是？",
        options: ["一律选 Tier IV", "按业务需求匹配，权衡可靠性与成本", "越低越好", "与成本无关"], answer: [1],
        explanation: "等级越高越贵，应匹配业务需求做成本/可靠性权衡。" },
    ],
    flashcards: [
      { id: "6-29-f1", front: "Uptime Tier I-IV", back: "I基础无冗余;II组件冗余;III可并行维护;IV容错。", chapterId: "6-29" },
      { id: "6-29-f2", front: "可并行维护 vs 容错", back: "TierIII可在线维护不停业务;TierIV任一突发故障不影响。", chapterId: "6-29" },
      { id: "6-29-f3", front: "国标分级", back: "GB 50174 分 A/B/C 三级，A 级最高。", chapterId: "6-29" },
    ],
  },

  // ---------------------- 第 30 章 ----------------------
  {
    id: "6-30",
    part: 6,
    index: "30",
    title: "监控与管理系统",
    summary: "DCIM、动环监控、关键指标与容量管理。",
    tier: 4,
    minutes: 22,
    objectives: [
      "理解 DCIM 与动环监控的范畴",
      "掌握需要监控的关键指标",
      "理解四类容量管理",
    ],
    blocks: [
      { type: "h2", text: "看不见就管不住" },
      { type: "p", text: "数据中心设备成千上万、7×24 运行，必须靠系统实时盯住一切，出问题第一时间告警。这就是监控管理系统的使命。" },
      { type: "table", headers: ["系统", "全称", "管什么"], rows: [
        ["DCIM", "数据中心基础设施管理", "统揽资产、容量、能耗、监控的综合平台"],
        ["动环监控", "动力环境监控", "温湿度、漏水、烟感、UPS、配电、门禁等"],
        ["BMS", "楼宇管理系统", "建筑层面的机电设备管理"],
      ] },
      { type: "knowledge", discipline: "英语", title: "DCIM 是个大筐", body: "DCIM(Data Center Infrastructure Management) 把资产管理、容量规划、能耗(PUE)分析、机房 3D 可视化、告警等整合在一个平台，帮运维“看全局、做决策”。动环监控更聚焦实时的物理量采集与告警，常作为 DCIM 的数据来源。" },
      { type: "h2", text: "关键监控指标" },
      { type: "list", items: [
        "**电**：各路电流/电压/功率、UPS 状态、电池、负载率；",
        "**冷**：各点温度、湿度、空调状态、冷冻水温/流量；",
        "**环境**：漏水、烟雾/火警、门禁、视频；",
        "**能效**：PUE 实时值（第 32 章细讲）；",
        "**IT**：机柜功率、空间(U)占用、网络状态。",
      ] },
      { type: "callout", variant: "warn", title: "告警要分级", body: "告警分级(提示/重要/紧急)，并设阈值，避免“告警风暴”淹没真正紧急的问题。比如温度超 27℃ 预警、超 35℃ 紧急。学会看监控、判断告警优先级，是运维的日常硬功夫。" },
      { type: "h2", text: "容量管理：别把家底用光" },
      { type: "p", text: "数据中心有四种“容量”，任何一种用满都无法再上设备。容量管理就是盯住这四条线，提前规划。" },
      { type: "table", headers: ["容量类型", "看什么"], rows: [
        ["电力容量", "供电/UPS 还能带多少 kW"],
        ["制冷容量", "制冷还能压住多少发热"],
        ["空间容量", "还有多少机柜/U 位"],
        ["网络容量", "端口、带宽还剩多少"],
      ] },
      { type: "callout", variant: "key", title: "电力常先告急", body: "实际中往往“空间还有、电不够了”——高密机柜让电力/制冷容量比空间更早触顶。所以容量管理里电与冷尤其关键，规划上架时要先算电够不够。" },
    ],
    quiz: [
      { id: "6-30-q1", kind: "single", question: "DCIM 的定位是？",
        options: ["只做制冷", "整合资产/容量/能耗/监控的综合管理平台", "一种服务器", "网络协议"], answer: [1],
        explanation: "DCIM 是综合管理平台，统揽资产、容量、能耗与监控。" },
      { id: "6-30-q2", kind: "single", question: "动环监控主要采集？",
        options: ["代码质量", "温湿度/漏水/烟感/配电/门禁等物理量", "网页访问量", "员工考勤"], answer: [1],
        explanation: "动环(动力环境)监控聚焦机房物理量与告警。" },
      { id: "6-30-q3", kind: "multi", question: "数据中心的四类容量包括？（多选）",
        options: ["电力容量", "制冷容量", "空间容量", "网络容量", "停车容量"],
        answer: [0, 1, 2, 3], explanation: "四类容量：电力、制冷、空间、网络。" },
      { id: "6-30-q4", kind: "single", question: "高密机柜场景下，通常最先触顶的容量是？",
        options: ["空间容量", "电力/制冷容量", "停车位", "网络端口"], answer: [1],
        explanation: "高密机柜常“空间还有、电与冷先不够”，需优先核算。" },
    ],
    flashcards: [
      { id: "6-30-f1", front: "DCIM vs 动环监控", back: "DCIM综合管理平台;动环监控实时采集物理量并告警(数据来源)。", chapterId: "6-30" },
      { id: "6-30-f2", front: "四类容量", back: "电力、制冷、空间、网络容量。", chapterId: "6-30" },
      { id: "6-30-f3", front: "告警分级", back: "按提示/重要/紧急分级设阈值，避免告警风暴。", chapterId: "6-30" },
    ],
  },

  // ---------------------- 第 31 章 ----------------------
  {
    id: "6-31",
    part: 6,
    index: "31",
    title: "运维流程与最佳实践",
    summary: "SOP/MOP/EOP、变更管理、巡检与 ITIL 入门。",
    tier: 4,
    minutes: 22,
    objectives: [
      "区分 SOP / MOP / EOP",
      "理解变更管理与巡检的意义",
      "了解 ITIL 的核心流程",
    ],
    blocks: [
      { type: "h2", text: "为什么运维要“按流程”" },
      { type: "p", text: "数据中心宕机的一大主因是**人为操作失误**。把操作标准化、流程化，让每个人按同样的正确步骤做事，是降低人为事故、保证可靠性的关键。" },
      { type: "h2", text: "三大操作规程：SOP / MOP / EOP" },
      { type: "table", headers: ["规程", "全称", "用于"], rows: [
        ["SOP", "标准操作规程", "日常例行操作的标准步骤"],
        ["MOP", "维护操作规程", "具体维护/变更作业的详细步骤(含风险与回退)"],
        ["EOP", "应急操作规程", "故障/紧急情况下的处置步骤"],
      ] },
      { type: "callout", variant: "key", title: "MOP 是高风险作业的护身符", body: "在带电/带业务的设备上动手前，要先写好 MOP：每一步怎么做、谁来做、风险是什么、出问题怎么回退，评审通过再执行。很多事故就是因为“没 MOP、凭经验干”。" },
      { type: "h2", text: "变更管理：改动必须可控" },
      { type: "p", text: "任何对生产环境的改动（上下架、改配置、维护）都要走**变更管理**：申请 → 评估风险 → 审批 → 选窗口期执行 → 验证 → 记录。目的是让改动“有计划、可追溯、可回退”，不打无准备之仗。" },
      { type: "h2", text: "巡检与故障处理" },
      { type: "list", items: [
        "**巡检**：定期按清单检查设备、环境、告警，把隐患消灭在故障前；",
        "**故障处理**：发现 → 定级 → 响应 → 按 EOP 处置 → 恢复 → 复盘(找根因、防复发)；",
        "**记录与复盘**：每次事件都要留痕、复盘，持续改进。",
      ] },
      { type: "h2", text: "ITIL：IT 服务管理框架" },
      { type: "knowledge", discipline: "英语", title: "ITIL 核心流程", body: "ITIL 是 IT 服务管理的最佳实践框架，常见流程：事件管理(Incident,快速恢复服务)、问题管理(Problem,找根因防复发)、变更管理(Change,可控变更)、配置管理(CMDB,资产台账)。运维岗常打交道，了解概念很加分。" },
      { type: "callout", variant: "tip", title: "心态提醒", body: "运维讲究“敬畏生产、按章操作、留痕复盘”。这种规范意识，比记住某个具体步骤更重要，也是面试官很看重的职业素养。" },
    ],
    quiz: [
      { id: "6-31-q1", kind: "single", question: "应急情况下的处置步骤规程是？",
        options: ["SOP", "MOP", "EOP", "ITIL"], answer: [2],
        explanation: "EOP=应急操作规程；SOP日常、MOP维护作业。" },
      { id: "6-31-q2", kind: "single", question: "在带业务设备上做维护前，应先准备？",
        options: ["什么都不用", "MOP(含步骤、风险与回退)并评审", "直接凭经验干", "先关掉监控"], answer: [1],
        explanation: "高风险作业须先编写并评审 MOP，明确步骤、风险与回退方案。" },
      { id: "6-31-q3", kind: "single", question: "变更管理的目的是？",
        options: ["让改动更随意", "让改动有计划、可追溯、可回退", "增加工作量", "取消审批"], answer: [1],
        explanation: "变更管理使生产改动可控：评估、审批、窗口执行、验证、记录。" },
      { id: "6-31-q4", kind: "single", question: "ITIL 中“找根因、防止复发”的是哪个流程？",
        options: ["事件管理", "问题管理", "配置管理", "变更管理"], answer: [1],
        explanation: "问题管理(Problem)聚焦根因分析与预防复发；事件管理重在快速恢复。" },
    ],
    flashcards: [
      { id: "6-31-f1", front: "SOP/MOP/EOP", back: "标准操作/维护操作(含回退)/应急操作 规程。", chapterId: "6-31" },
      { id: "6-31-f2", front: "变更管理目的", back: "让生产改动有计划、可追溯、可回退(申请→评估→审批→执行→验证)。", chapterId: "6-31" },
      { id: "6-31-f3", front: "故障处理流程", back: "发现→定级→响应→按EOP处置→恢复→复盘找根因。", chapterId: "6-31" },
      { id: "6-31-f4", front: "ITIL核心流程", back: "事件(快速恢复)、问题(找根因)、变更(可控)、配置(台账)。", chapterId: "6-31" },
    ],
  },

  // ---------------------- 第 32 章 ----------------------
  {
    id: "6-32",
    part: 6,
    index: "32",
    title: "能效与绿色数据中心",
    summary: "PUE/WUE、节能手段、可再生能源与可持续。",
    tier: 4,
    minutes: 22,
    objectives: [
      "掌握 PUE/WUE 的定义与计算",
      "了解主流节能手段",
      "把握绿色数据中心趋势与监管",
    ],
    blocks: [
      { type: "h2", text: "PUE：最重要的能效指标" },
      { type: "callout", variant: "key", title: "PUE = 数据中心总用电 ÷ IT 设备用电", body: "PUE 越接近 1 越好。PUE=2 表示 IT 每用 1 度电，配套(制冷/供电损耗等)也要用 1 度；PUE=1.3 表示配套只多花 0.3 度。它直接衡量“有多少电真正用在了计算上”。" },
      { type: "widget", widget: "pue", title: "动手试试：PUE 计算器" },
      { type: "knowledge", discipline: "数学", title: "PUE 的构成", body: "总用电=IT用电+制冷+供电损耗(UPS/变压器)+照明等。制冷通常是 IT 之外最大的耗电项，所以节能的主战场在制冷。理想 PUE=1.0(不可能达到)，现代先进数据中心可做到 1.1–1.3。" },
      { type: "table", headers: ["指标", "含义", "目标"], rows: [
        ["PUE", "电能使用效率=总电÷IT电", "越接近1越好"],
        ["WUE", "水使用效率=用水量÷IT电", "越低越省水"],
        ["CUE", "碳使用效率=碳排÷IT电", "越低越环保"],
      ] },
      { type: "h2", text: "怎么降 PUE：节能手段" },
      { type: "list", items: [
        "**制冷优化**：冷热通道封闭、提高送风温度、**自然冷却**(最有效)；",
        "**高效设备**：高效 UPS、变压器，减少转换损耗；",
        "**液冷**：高密度场景大幅提升散热效率；",
        "**精细化运营**：按需制冷、关停闲置设备、用 DCIM 持续优化。",
      ] },
      { type: "h2", text: "绿色与可持续" },
      { type: "list", items: [
        "**可再生能源**：用风电、光伏等绿电供电，降低碳排；",
        "**余热利用**：把机房废热用于供暖等，变废为宝；",
        "**节水**：优化或减少冷却塔耗水(关注 WUE)；",
        "**监管趋严**：国内对新建数据中心 PUE 有明确限值要求(如先进地区要求 PUE≤1.25 左右)，达不到不让建。",
      ] },
      { type: "callout", variant: "tip", title: "为什么能效如此重要", body: "数据中心是耗电大户，电费占运营成本很大比例。降 PUE 既省钱又环保，还是合规的硬要求。所以“能效”是贯穿设计、设备、运营的核心主题，也是行业最热的方向之一。" },
    ],
    quiz: [
      { id: "6-32-q1", kind: "single", question: "PUE 的定义是？",
        options: ["IT用电÷总用电", "总用电÷IT用电，越接近1越好", "制冷÷供电", "总用电×IT用电"], answer: [1],
        explanation: "PUE=数据中心总用电÷IT设备用电，越接近1越节能。" },
      { id: "6-32-q2", kind: "single", question: "PUE=1.5 表示？",
        options: ["IT每用1度，配套再用0.5度", "完全不耗配套电", "IT用电是总电的1.5倍", "无意义"], answer: [0],
        explanation: "PUE=1.5 即每 1 度 IT 用电，配套(制冷/损耗)再用 0.5 度。" },
      { id: "6-32-q3", kind: "single", question: "降低 PUE 最有效的方向通常是？",
        options: ["增加照明", "制冷优化(自然冷却/通道封闭/提温)", "提高电压", "增加服务器"], answer: [1],
        explanation: "制冷是 IT 外最大耗电项，制冷优化(尤其自然冷却)最有效。" },
      { id: "6-32-q4", kind: "single", question: "WUE 衡量的是？",
        options: ["电能效率", "水使用效率", "碳排放", "网络速度"], answer: [1],
        explanation: "WUE=用水量÷IT用电，衡量节水；CUE 衡量碳排。" },
    ],
    flashcards: [
      { id: "6-32-f1", front: "PUE定义", back: "总用电÷IT用电，越接近1越节能。", chapterId: "6-32" },
      { id: "6-32-f2", front: "PUE构成与主战场", back: "总电=IT+制冷+供电损耗+照明；制冷是节能主战场。", chapterId: "6-32" },
      { id: "6-32-f3", front: "降PUE手段", back: "自然冷却、通道封闭、提温、高效UPS、液冷、精细运营。", chapterId: "6-32" },
      { id: "6-32-f4", front: "PUE/WUE/CUE", back: "电/水/碳 使用效率，均越低越好。", chapterId: "6-32" },
    ],
  },
];
