import { Chapter } from "@/lib/types";

// ============================================================
// 第 11 部分　自动化与可观测性（云原生主线，归入进阶地图 L5）
// ============================================================

export const PART11: Chapter[] = [
  // ---------------------- 11-1 ----------------------
  {
    id: "11-1",
    part: 11,
    index: "A1",
    title: "Shell 脚本基础",
    summary: "把重复命令写成脚本：变量、条件、循环、运维常用套路。",
    tier: 5,
    minutes: 24,
    objectives: ["理解为什么运维要会 Shell", "掌握变量/条件/循环基本语法", "能写出一个简单的运维脚本"],
    blocks: [
      { type: "h2", text: "运维进阶的第一道分水岭" },
      { type: "p", text: "手动一条条敲命令，做一次还行，做一百次就该让机器代劳。**Shell 脚本**就是把一串命令写进文件、一键执行，是运维“把重复劳动自动化”的起点。Linux 默认的 Shell 是 **Bash**。" },
      { type: "h2", text: "最小语法集" },
      { type: "list", items: [
        "脚本开头 `#!/bin/bash`（指定解释器），存为 `x.sh`，`chmod +x x.sh` 后 `./x.sh` 运行",
        "**变量**：`name=web`（等号两边不留空格），用 `$name` 取值",
        "**条件**：`if [ -f /etc/nginx/nginx.conf ]; then ... fi`",
        "**循环**：`for s in web db cache; do echo $s; done`",
        "**取命令输出**：`now=$(date)`",
        "**参数**：`$1 $2` 是传给脚本的第 1、2 个参数",
      ] },
      { type: "knowledge", discipline: "计算机", title: "退出码：脚本如何判断成败", body: "每条命令执行后都有一个“退出码”，`$?` 取它：0 表示成功、非 0 表示失败。脚本里常用它判断上一步是否成功再决定下一步——这也是 CI/CD、自动化里“某步失败就停”的底层依据。" },
      { type: "h2", text: "一个实用例子：批量检查服务" },
      { type: "list", ordered: true, items: [
        "用 `for` 遍历服务名列表",
        "对每个服务 `systemctl is-active 服务名` 判断是否在跑",
        "用 `if` 判断结果，打印 ✅/❌",
        "异常时可顺手 `echo` 记日志或发通知",
      ] },
      { type: "callout", variant: "tip", title: "🧪 动手练", body: "在你的 Linux 虚拟机/homelab 上写一个 `check.sh`：遍历 `nginx sshd` 两个服务，逐个打印运行状态。再加个 `$1` 参数让它能检查任意指定服务。" },
      { type: "callout", variant: "info", title: "RHCE 与脚本", body: "Shell 脚本是 Linux 运维的基本功，也是 RHCE 的考点之一。先把它练顺，后面学 Ansible 会更轻松——本质都是“把操作自动化”。" },
    ],
    quiz: [
      { id: "11-1-q1", kind: "single", question: "Bash 脚本第一行通常写什么？", options: ["#include", "#!/bin/bash", "import bash", "<script>"], answer: [1], explanation: "#!/bin/bash（shebang）指定用 bash 解释执行该脚本。" },
      { id: "11-1-q2", kind: "single", question: "取上一条命令是否成功，用？", options: ["$1", "$?", "$name", "$0"], answer: [1], explanation: "$? 是上一条命令的退出码，0 成功、非 0 失败。" },
      { id: "11-1-q3", kind: "single", question: "Shell 中给变量赋值正确的是？", options: ["name = web", "name=web", "let name web", "var name=web"], answer: [1], explanation: "Bash 变量赋值等号两边不能有空格：name=web。" },
      { id: "11-1-q4", kind: "single", question: "遍历一组值用哪种结构？", options: ["if", "for ... do ... done", "case", "function"], answer: [1], explanation: "for s in a b c; do ...; done 用于遍历列表。" },
    ],
    flashcards: [
      { id: "11-1-f1", front: "Shell 脚本怎么跑", back: "#!/bin/bash 开头 → chmod +x x.sh → ./x.sh。", chapterId: "11-1" },
      { id: "11-1-f2", front: "变量与取值", back: "name=web(无空格)，用 $name 取值；$(cmd) 取命令输出。", chapterId: "11-1" },
      { id: "11-1-f3", front: "退出码 $?", back: "上条命令退出码，0成功/非0失败，用于判断流程成败。", chapterId: "11-1" },
      { id: "11-1-f4", front: "条件与循环", back: "if [ 条件 ]; then..fi；for x in 列表; do..done。", chapterId: "11-1" },
    ],
  },

  // ---------------------- 11-2 ----------------------
  {
    id: "11-2",
    part: 11,
    index: "A2",
    title: "Python 运维入门",
    summary: "运维为什么要会 Python、基础语法、处理文件与调用 API。",
    tier: 5,
    minutes: 24,
    objectives: ["理解 Python 在运维中的角色", "掌握最基础的 Python 语法", "知道用 Python 做哪些运维任务"],
    blocks: [
      { type: "h2", text: "Shell 之外，为什么还要 Python" },
      { type: "p", text: "Shell 擅长串联命令，但一旦逻辑复杂（解析 JSON、调用 API、处理数据、写工具），就该上 **Python**：语法清晰、库丰富、跨平台。现代运维/SRE 几乎都要求会一门脚本语言，Python 是最通用的选择。" },
      { type: "h2", text: "最小语法集" },
      { type: "list", items: [
        "**变量**：`name = 'web'`（动态类型，不用声明类型）",
        "**条件**：`if x > 0:` 下一行缩进（Python 用缩进表示代码块）",
        "**循环**：`for s in ['web','db']:`",
        "**函数**：`def check(name): ...`",
        "**库**：`import os, json, requests`（标准库 + 第三方）",
      ] },
      { type: "knowledge", discipline: "计算机", title: "缩进就是语法", body: "和大多数语言用 {} 不同，Python 用**缩进**划分代码块——同一块代码缩进必须一致（通常 4 个空格）。这逼着代码保持整洁，但也意味着缩进错了程序就报错或行为变样，初学要特别注意。" },
      { type: "h2", text: "运维常用 Python 做什么" },
      { type: "list", items: [
        "**处理文件/日志**：批量读写、按规则提取（比 Shell 更顺手）",
        "**调用 API**：用 `requests` 调云厂商/监控/K8s 的 API 做自动化",
        "**解析数据**：`json`/`yaml` 解析配置与返回",
        "**写小工具/告警机器人**：定时巡检、异常通知",
        "**Ansible、众多云 SDK 都是 Python 生态**，会 Python 如虎添翼",
      ] },
      { type: "callout", variant: "tip", title: "🧪 动手练", body: "写一个 `disk.py`：用 `shutil.disk_usage('/')` 读取磁盘使用率，超过 80% 就打印告警。再尝试用 `requests` 拉取一个公开 API 的 JSON 并打印其中一个字段。" },
      { type: "callout", variant: "info", title: "学到什么程度", body: "入门阶段不必精通，能读懂、能改、能写小脚本即可。随着做自动化和调 API，Python 会自然越用越熟。先建立“遇到复杂逻辑就用 Python”的习惯。" },
    ],
    quiz: [
      { id: "11-2-q1", kind: "single", question: "Python 用什么划分代码块？", options: ["大括号 {}", "缩进", "分号", "关键字 begin/end"], answer: [1], explanation: "Python 用缩进表示代码块，同块缩进必须一致(通常4空格)。" },
      { id: "11-2-q2", kind: "single", question: "相比 Shell，更适合用 Python 的场景是？", options: ["简单串联几条命令", "复杂逻辑：解析JSON、调API、处理数据", "改文件权限", "看磁盘"], answer: [1], explanation: "逻辑复杂、需解析数据/调用API时，Python 比 Shell 更顺手。" },
      { id: "11-2-q3", kind: "single", question: "Python 中调用 HTTP API 常用的库是？", options: ["nginx", "requests", "systemctl", "grep"], answer: [1], explanation: "requests 是最常用的 HTTP 库，用于调用各类 API。" },
      { id: "11-2-q4", kind: "single", question: "关于运维学 Python，正确的是？", options: ["必须先精通才有用", "能读懂能写小脚本即可，越用越熟", "运维用不到", "只能在Windows用"], answer: [1], explanation: "入门能读会改会写小工具即可，结合自动化逐步精进。" },
    ],
    flashcards: [
      { id: "11-2-f1", front: "为何运维要会 Python", back: "复杂逻辑/解析数据/调API/写工具；Ansible与云SDK都是Python生态。", chapterId: "11-2" },
      { id: "11-2-f2", front: "Python 代码块", back: "用缩进(通常4空格)划分，缩进错会报错或行为变样。", chapterId: "11-2" },
      { id: "11-2-f3", front: "运维常用 Python 做", back: "处理文件/日志、调API(requests)、解析json/yaml、写巡检告警工具。", chapterId: "11-2" },
    ],
  },

  // ---------------------- 11-3 ----------------------
  {
    id: "11-3",
    part: 11,
    index: "A3",
    title: "Git 版本控制",
    summary: "为什么人人要会 Git、核心命令、分支与协作。",
    tier: 5,
    minutes: 22,
    objectives: ["理解 Git 解决什么问题", "掌握 add/commit/push/pull 核心流程", "理解分支与基本协作"],
    blocks: [
      { type: "h2", text: "Git：代码与配置的“时光机”" },
      { type: "p", text: "**Git** 是分布式版本控制系统，记录每一次改动、能回到任意历史版本、能多人协作不互相覆盖。如今它不只是程序员的工具——运维的脚本、配置、IaC（基础设施即代码）、CI/CD 全都靠 Git 管理。你这个学习网站本身也是用 Git + GitHub 部署的。" },
      { type: "h2", text: "核心流程（记住这条链）" },
      { type: "table", headers: ["命令", "作用"], rows: [
        ["git clone 地址", "把远程仓库下载到本地"],
        ["git status", "看改了哪些文件"],
        ["git add .", "把改动加入暂存区"],
        ["git commit -m \"说明\"", "把暂存的改动记录成一个版本"],
        ["git push", "把本地提交推送到远程(如 GitHub)"],
        ["git pull", "把远程最新改动拉到本地"],
        ["git log", "看提交历史"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "工作区 → 暂存区 → 仓库", body: "Git 有三个区：你改文件在“工作区”；`git add` 把改动放进“暂存区”（挑选这次要提交什么）；`git commit` 把暂存区固化成一个版本进“本地仓库”；`git push` 再同步到远程。理解这三步，就不会被 add/commit 搞晕。" },
      { type: "h2", text: "分支：并行开发不打架" },
      { type: "list", items: [
        "`git branch` 看分支，`git checkout -b 新分支` 建并切换",
        "在分支上改动、提交，不影响主分支(main)",
        "改好后通过**合并(merge)** 或 **Pull Request** 并回主分支",
        "多人协作时，各开各的分支、最后合并，互不覆盖",
      ] },
      { type: "callout", variant: "tip", title: "🧪 动手练", body: "在 GitHub 建个练习仓库 → `git clone` 到本地 → 改个文件 → `add`/`commit`/`push` → 在 GitHub 上看到更新。再建一个分支改点东西、发起 Pull Request 合并，体会协作流程。" },
      { type: "callout", variant: "key", title: "GitOps 预告", body: "云原生里有个理念叫 **GitOps**：把基础设施和部署的“期望状态”全写进 Git，改 Git 即改系统（如 ArgoCD 自动同步到 K8s）。所以 Git 是云原生自动化的中枢，务必练熟。" },
    ],
    quiz: [
      { id: "11-3-q1", kind: "single", question: "把本地提交同步到 GitHub 用？", options: ["git pull", "git push", "git add", "git status"], answer: [1], explanation: "git push 推送本地提交到远程；git pull 是拉取远程更新。" },
      { id: "11-3-q2", kind: "single", question: "把改动放进暂存区、准备提交用？", options: ["git commit", "git add", "git clone", "git log"], answer: [1], explanation: "git add 把改动加入暂存区，再用 git commit 固化成版本。" },
      { id: "11-3-q3", kind: "single", question: "Git 的三个区正确顺序是？", options: ["仓库→暂存区→工作区", "工作区→暂存区→仓库", "暂存区→工作区→仓库", "没有分区"], answer: [1], explanation: "改动在工作区 → add 到暂存区 → commit 进本地仓库。" },
      { id: "11-3-q4", kind: "single", question: "想并行开发又不影响主分支，应该？", options: ["直接改 main", "新建分支开发，完成后合并/PR", "复制整个项目", "删掉历史"], answer: [1], explanation: "新建分支独立开发，完成后通过 merge/PR 并回主分支。" },
    ],
    flashcards: [
      { id: "11-3-f1", front: "Git 核心流程", back: "clone→改→add→commit -m→push；拉更新用 pull。", chapterId: "11-3" },
      { id: "11-3-f2", front: "Git 三个区", back: "工作区(改)→暂存区(add)→本地仓库(commit)→远程(push)。", chapterId: "11-3" },
      { id: "11-3-f3", front: "分支协作", back: "checkout -b 建分支，独立改提交，merge/PR 合回 main，多人不打架。", chapterId: "11-3" },
      { id: "11-3-f4", front: "GitOps", back: "把期望状态写进Git，改Git即改系统(ArgoCD同步K8s)，Git是云原生中枢。", chapterId: "11-3" },
    ],
  },

  // ---------------------- 11-4 ----------------------
  {
    id: "11-4",
    part: 11,
    index: "A4",
    title: "Ansible 自动化运维",
    summary: "无 agent 的批量自动化：inventory、playbook、幂等，从 Mac 管联想。",
    tier: 5,
    minutes: 26,
    objectives: ["理解 Ansible 的工作方式与优势", "看懂 inventory 与 playbook", "理解幂等性，并能在两台机器上跑通"],
    blocks: [
      { type: "h2", text: "从“一台台敲”到“一键管一片”" },
      { type: "p", text: "服务器多了，挨个 SSH 上去配置既慢又容易不一致。**Ansible** 让你在一台“控制端”写好剧本，**通过 SSH 批量**对一群机器执行同样的配置——不用在被管机器上装任何 agent，这是它最大的优势。" },
      { type: "h2", text: "三个核心概念" },
      { type: "list", items: [
        "**Inventory（清单）**：列出要管理的主机（IP/分组），如 `[web]` 组下放几台机器",
        "**Module（模块）**：Ansible 内置的“能力”，如装包、拷文件、起服务",
        "**Playbook（剧本）**：用 YAML 写的任务清单，声明“目标机器要变成什么样”，按顺序执行多个任务",
      ] },
      { type: "knowledge", discipline: "计算机", title: "幂等性：重复跑也安全", body: "Ansible 的任务是**幂等**的——同一个 playbook 跑一次和跑十次，结果一样：已经是期望状态就跳过，不会重复装/重复改。这让你能放心反复执行，是“声明式”思想（和 K8s 一脉相承）在配置管理上的体现。" },
      { type: "h2", text: "一个 playbook 长什么样（概念）" },
      { type: "list", items: [
        "`hosts: web` —— 对哪组机器执行",
        "`tasks:` 下列若干任务，每个任务调一个模块：",
        "　- 用 `apt`/`yum` 模块装 nginx",
        "　- 用 `copy`/`template` 模块下发配置文件",
        "　- 用 `service` 模块确保 nginx 启动并开机自启",
        "执行：`ansible-playbook -i inventory site.yml`",
      ] },
      { type: "callout", variant: "key", title: "🧪 动手练（你的两台机器联动）", body: "把 Mac 当控制端、联想当被管机：①Mac 上 `ssh-copy-id` 配好免密登录联想 ②写 inventory 把联想 IP 放进 [lab] 组 ③写个 playbook 在联想上装 nginx 并启动 ④`ansible-playbook` 一键执行 ⑤浏览器访问联想 IP 看到 nginx。这就是真实运维“一处编写、批量执行”的核心体验。" },
      { type: "callout", variant: "info", title: "Ansible 与 RHCE", body: "RHCE（红帽认证工程师）的核心考点就是 Ansible 自动化。把上面的 playbook 练熟、理解幂等，既是工作硬技能，也是直接对标 RHCE。" },
    ],
    quiz: [
      { id: "11-4-q1", kind: "single", question: "Ansible 最大的特点之一是？", options: ["需在每台被管机装agent", "无需agent，通过SSH批量执行", "只能管1台", "只能用图形界面"], answer: [1], explanation: "Ansible 无需 agent，借助 SSH 批量对多机执行配置。" },
      { id: "11-4-q2", kind: "single", question: "列出要管理的主机及分组的是？", options: ["Playbook", "Inventory", "Module", "Role"], answer: [1], explanation: "Inventory 清单定义被管主机与分组。" },
      { id: "11-4-q3", kind: "single", question: "“同一剧本跑多次结果一致、不重复操作”叫？", options: ["并发性", "幂等性", "原子性", "持久性"], answer: [1], explanation: "幂等性：达到期望状态就跳过，反复执行安全。" },
      { id: "11-4-q4", kind: "single", question: "Ansible 是哪个认证的核心考点？", options: ["CCNA", "RHCE", "PMP", "CDCP"], answer: [1], explanation: "RHCE 的核心就是 Ansible 自动化。" },
    ],
    flashcards: [
      { id: "11-4-f1", front: "Ansible 是什么", back: "无agent、走SSH的批量自动化工具；一处编写、批量执行。", chapterId: "11-4" },
      { id: "11-4-f2", front: "三核心概念", back: "Inventory(主机清单)、Module(能力)、Playbook(YAML任务剧本)。", chapterId: "11-4" },
      { id: "11-4-f3", front: "幂等性", back: "同剧本跑多次结果一致、已达标就跳过；声明式思想。", chapterId: "11-4" },
      { id: "11-4-f4", front: "Ansible 对标", back: "RHCE 核心考点；Mac控制端→Ansible→联想被管机=真实运维。", chapterId: "11-4" },
    ],
  },

  // ---------------------- 11-5 ----------------------
  {
    id: "11-5",
    part: 11,
    index: "A5",
    title: "监控：Prometheus + Grafana",
    summary: "指标采集、PromQL、可视化大盘与告警。",
    tier: 5,
    minutes: 24,
    objectives: ["理解监控为什么是运维刚需", "认识 Prometheus + Grafana 的分工", "理解指标、告警与“四个黄金信号”"],
    blocks: [
      { type: "h2", text: "看不见，就管不好" },
      { type: "p", text: "系统在跑，但 CPU 多高？内存够不够？请求有没有变慢？出问题前有没有征兆？**监控/可观测性**就是给系统装上“仪表盘和体检报告”，让你从“等用户报障”变成“提前发现、主动处置”。" },
      { type: "h2", text: "云原生监控黄金搭档" },
      { type: "table", headers: ["工具", "角色"], rows: [
        ["Prometheus", "采集与存储**指标**(时序数据)，并按规则触发告警"],
        ["Grafana", "把指标画成漂亮的**可视化大盘**(Dashboard)"],
        ["Alertmanager", "管理告警的分组、去重与通知(邮件/钉钉等)"],
        ["Exporter", "暴露被监控对象的指标(如 node_exporter 采集主机指标)"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "指标 / 日志 / 链路：可观测性三支柱", body: "可观测性有三类数据：**Metrics 指标**(数值，如CPU%、QPS，本章重点)、**Logs 日志**(文本事件，下一章)、**Traces 链路追踪**(一个请求在多个服务间的路径)。三者配合，才能既看到“哪里不对”，又查到“为什么不对”。" },
      { type: "h2", text: "盯什么：四个黄金信号" },
      { type: "list", items: [
        "**延迟(Latency)**：请求耗时",
        "**流量(Traffic)**：请求量/吞吐",
        "**错误(Errors)**：失败率",
        "**饱和度(Saturation)**：资源用到多满(CPU/内存/磁盘)",
        "盯住这四个，就抓住了系统健康的主要矛盾",
      ] },
      { type: "callout", variant: "info", title: "PromQL 与告警", body: "Prometheus 用查询语言 **PromQL** 取指标，比如算某接口 5 分钟内的错误率；当表达式满足条件(如错误率>5%持续5分钟)就触发告警，经 Alertmanager 通知到人。" },
      { type: "callout", variant: "tip", title: "🧪 动手练", body: "在 homelab(联想或 K8s)上用 Docker 跑 Prometheus + node_exporter + Grafana：Grafana 加 Prometheus 数据源，导入一个主机监控大盘，实时看 CPU/内存/磁盘曲线。再设一条“磁盘>80%”的告警规则。" },
    ],
    quiz: [
      { id: "11-5-q1", kind: "single", question: "Prometheus 和 Grafana 的分工是？", options: ["都只画图", "Prometheus采集存储指标+告警，Grafana可视化", "Grafana采集，Prometheus画图", "都用于写代码"], answer: [1], explanation: "Prometheus 负责采集/存储指标与告警，Grafana 负责可视化大盘。" },
      { id: "11-5-q2", kind: "single", question: "可观测性的三支柱是？", options: ["增删改查", "指标 / 日志 / 链路追踪", "CPU/内存/磁盘", "前端/后端/数据库"], answer: [1], explanation: "Metrics 指标、Logs 日志、Traces 链路追踪是可观测性三支柱。" },
      { id: "11-5-q3", kind: "single", question: "下列哪个不是“四个黄金信号”？", options: ["延迟", "流量", "错误", "颜色"], answer: [3], explanation: "四个黄金信号是延迟、流量、错误、饱和度。" },
      { id: "11-5-q4", kind: "single", question: "采集主机 CPU/内存等指标常用？", options: ["node_exporter", "nginx", "git", "ssh"], answer: [0], explanation: "node_exporter 暴露主机指标供 Prometheus 采集。" },
    ],
    flashcards: [
      { id: "11-5-f1", front: "监控黄金搭档", back: "Prometheus(采集/存指标/告警)+Grafana(可视化)+Alertmanager(通知)+Exporter(暴露指标)。", chapterId: "11-5" },
      { id: "11-5-f2", front: "可观测性三支柱", back: "Metrics指标、Logs日志、Traces链路追踪。", chapterId: "11-5" },
      { id: "11-5-f3", front: "四个黄金信号", back: "延迟、流量、错误、饱和度。", chapterId: "11-5" },
      { id: "11-5-f4", front: "PromQL/告警", back: "用PromQL查指标，满足条件触发告警→Alertmanager通知。", chapterId: "11-5" },
    ],
  },

  // ---------------------- 11-6 ----------------------
  {
    id: "11-6",
    part: 11,
    index: "A6",
    title: "日志与 SRE 思维",
    summary: "日志体系、SLO/SLI/错误预算、故障复盘与 on-call。",
    tier: 5,
    minutes: 24,
    objectives: ["了解集中式日志体系", "理解 SLI/SLO/错误预算", "建立故障复盘与 on-call 的工程文化认知"],
    blocks: [
      { type: "h2", text: "日志：出事后的“黑匣子”" },
      { type: "p", text: "指标告诉你“哪里不对”，**日志**告诉你“为什么不对”。机器一多，登录每台翻日志不现实，于是有了**集中式日志**：把各处日志统一收集、存储、检索。" },
      { type: "list", items: [
        "**ELK/EFK**：Elasticsearch(存/搜) + Logstash/Fluentd(收集) + Kibana(查询展示)",
        "**Loki + Grafana**：更轻量的云原生日志方案，和 Grafana 同屏看指标+日志",
        "核心价值：一处搜索，快速定位某时间段、某服务的报错",
      ] },
      { type: "h2", text: "SRE：用工程方法保障可靠性" },
      { type: "p", text: "**SRE（站点可靠性工程）** 是 Google 提出的运维理念：用软件工程的方法管理系统可靠性。几个关键概念：" },
      { type: "table", headers: ["概念", "含义"], rows: [
        ["SLI（指标）", "衡量服务质量的具体指标，如成功率、延迟"],
        ["SLO（目标）", "对 SLI 设定的目标，如“可用性 99.9%”"],
        ["错误预算", "100% 减去 SLO 的容错空间(如 0.1%)，用完就该停下来先稳定而非赶新功能"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "错误预算：可靠性与速度的平衡器", body: "追求 100% 可用既不现实也不划算。SLO 定一个“足够好”的目标(如 99.9%)，剩下的 0.1% 就是“错误预算”——还有预算就可以大胆上线迭代；预算快用完就放慢、先补稳定性。它把“稳定 vs 快”的争论变成了可量化的决策。" },
      { type: "h2", text: "故障复盘与 on-call" },
      { type: "list", items: [
        "**On-call（值班）**：轮流响应告警，及时处置线上问题",
        "**故障复盘(Postmortem)**：事后还原时间线、找根因、定改进项",
        "**对事不对人(Blameless)**：复盘聚焦系统与流程改进，不追责个人，鼓励如实暴露问题",
        "**从每次故障中沉淀改进**，让系统越来越稳——这正是你那个“学→错→复盘→强化”闭环在工程上的放大版",
      ] },
      { type: "callout", variant: "key", title: "你已经在用 SRE 思维了", body: "本站的「错题本 + 复盘 + 重测」闭环，和 SRE 的「故障 → 无责复盘 → 改进 → 验证」是同一套方法论：把错误当作改进的燃料。把这套思维带到工作里，你会成长得很快。" },
      { type: "callout", variant: "tip", title: "🧪 动手练", body: "给你 homelab 的某个服务定一个 SLO(如“可用性 99%”)；用监控观察一段时间；模拟一次故障(停掉服务)，事后写一份简短复盘：时间线、根因、改进项。走一遍，你就懂 SRE 了。" },
    ],
    quiz: [
      { id: "11-6-q1", kind: "single", question: "指标与日志的分工是？", options: ["指标查原因、日志看趋势", "指标告诉哪里不对、日志告诉为什么不对", "两者相同", "日志只存图片"], answer: [1], explanation: "指标反映状态(哪里不对)，日志记录事件细节(为什么不对)。" },
      { id: "11-6-q2", kind: "single", question: "“可用性 99.9%”这类对服务质量设定的目标叫？", options: ["SLI", "SLO", "SSH", "SLA合同细则"], answer: [1], explanation: "SLO 是对 SLI 设定的目标值；SLI 是具体指标。" },
      { id: "11-6-q3", kind: "single", question: "错误预算的作用是？", options: ["越多越好", "量化可靠性与迭代速度的平衡：预算用完就先稳定", "等于零", "与SLO无关"], answer: [1], explanation: "错误预算=100%-SLO，用它平衡“求稳”与“求快”。" },
      { id: "11-6-q4", kind: "single", question: "故障复盘提倡的文化是？", options: ["追责个人", "对事不对人(无责复盘)，聚焦系统改进", "隐瞒问题", "不复盘"], answer: [1], explanation: "Blameless 复盘聚焦系统/流程改进，鼓励如实暴露问题。" },
    ],
    flashcards: [
      { id: "11-6-f1", front: "集中式日志方案", back: "ELK/EFK(ES+Logstash/Fluentd+Kibana)、Loki+Grafana(轻量云原生)。", chapterId: "11-6" },
      { id: "11-6-f2", front: "SLI/SLO/错误预算", back: "SLI具体指标、SLO目标值(如99.9%)、错误预算=100%-SLO。", chapterId: "11-6" },
      { id: "11-6-f3", front: "错误预算意义", back: "量化“稳vs快”：有预算可迭代，将耗尽则放慢补稳定。", chapterId: "11-6" },
      { id: "11-6-f4", front: "无责复盘", back: "Postmortem 对事不对人，还原时间线找根因定改进，故障中沉淀。", chapterId: "11-6" },
    ],
  },
];
