import { Chapter } from "@/lib/types";

export const PART0: Chapter[] = [
  // ----------------------------------------------------------
  {
    id: "0-1",
    part: 0,
    index: "0.1",
    title: "学习方法与如何用好本站",
    summary: "先学会怎么学，再开始学什么。把这个网站用到位。",
    tier: 1,
    minutes: 12,
    objectives: [
      "理解为什么零基础要先补“底层学科”再学数据中心",
      "掌握本站的学习闭环：读 → 练 → 测 → 记 → 升段",
      "学会用进度、笔记、抽认卡、资源库四件工具",
    ],
    blocks: [
      { type: "h2", text: "欢迎，未来的数据中心工程师" },
      { type: "p", text: "数据中心是支撑整个互联网的“数字工厂”——你刷的每一条视频、发的每一条消息，背后都有一座座机房在运转。这个行业**门槛清晰、需求长期、待遇不错**，而且非常适合系统学习后转行进入。" },
      { type: "p", text: "你是零基础转行，目标是**全面综合**地掌握数据中心。所以我们不急着背术语，而是先打通底层：一点点**英语、数学、物理、计算机、通信**——只学和数据中心相关的部分。地基牢，后面才学得快、学得稳。" },
      { type: "callout", variant: "key", title: "核心理念", body: "数据中心 = 一栋为“服务器”持续供电、持续散热、持续联网的建筑。后面所有知识，都是围绕“供电、散热、联网、不能停”这四件事展开的。记住这条主线，再多术语都不会乱。" },
      { type: "h2", text: "本站的学习闭环" },
      { type: "p", text: "每一章都遵循同一个节奏，照着走就行：" },
      { type: "list", ordered: true, items: [
        "**读**：正文讲解，遇到不懂的底层概念会有“即时知识卡”一点就展开；",
        "**练**：动手做章节里的计算器、拖拽、决策题（真正在浏览器里操作）；",
        "**测**：章末自测题，检验是否真懂，错题有详细解析；",
        "**记**：把核心知识点加入“抽认卡”，靠间隔复习长期记牢；",
        "**升段**：完成知识关 + 实操关，点亮段位徽章，解锁下一段。",
      ] },
      { type: "h2", text: "你的四件工具" },
      { type: "table", headers: ["工具", "作用", "在哪用"], rows: [
        ["进度跟踪", "记录已学章节、自测分数，自动算出你的段位", "首页仪表盘"],
        ["笔记", "每章可写笔记，沉淀自己的理解", "每章底部 / 笔记页"],
        ["抽认卡", "把要点做成卡片，按遗忘曲线复习", "抽认卡页"],
        ["资源库", "外部优质资源导航，每周自动更新", "资源库页"],
      ] },
      { type: "callout", variant: "tip", title: "学习节奏建议", body: "每天 30–60 分钟，先过第 0 部分（基础垫脚石），再按部分顺序推进。每学完一章一定要做自测题——“以为懂”和“真的懂”差距很大。" },
      { type: "callout", variant: "info", title: "关于数据同步", body: "你的进度默认存在本机浏览器。若你在多台设备学习，去“设置”里输入访问口令开启云同步，进度就会自动跟着你走。也可随时导出备份。" },
    ],
    quiz: [
      { id: "0-1-q1", kind: "single", question: "本站建议零基础学员的学习顺序是？",
        options: ["直接背数据中心术语", "先补相关的底层学科，再学数据中心", "只做练习题", "只看视频资源"],
        answer: [1], explanation: "地基（数理、计算机、通信、英语）打牢，后面学专业内容会快很多，这正是第 0 部分存在的意义。" },
      { id: "0-1-q2", kind: "single", question: "贯穿数据中心所有知识的“主线”是？",
        options: ["供电、散热、联网、不能停", "编程、算法、数据库", "焊接、布线、搬运", "买卖服务器"],
        answer: [0], explanation: "数据中心的本质是为服务器持续供电、散热、联网且不能中断，记住这条主线能帮你串起所有知识。" },
      { id: "0-1-q3", kind: "tf", question: "“以为自己懂了”就可以跳过章末自测题。",
        options: ["正确", "错误"], answer: [1],
        explanation: "自测是检验真懂的关键环节，错题解析往往能纠正理解偏差，务必每章都做。" },
    ],
    flashcards: [
      { id: "0-1-f1", front: "数据中心的本质（一句话）", back: "一栋为服务器持续供电、散热、联网、且不能停的建筑。", chapterId: "0-1" },
      { id: "0-1-f2", front: "本站学习闭环的五步", back: "读 → 练 → 测 → 记 → 升段。", chapterId: "0-1" },
    ],
  },

  // ----------------------------------------------------------
  {
    id: "0-2",
    part: 0,
    index: "0.2",
    title: "专业英语入门",
    summary: "数据中心的权威资料和认证大多是英文。掌握核心术语与缩写。",
    tier: 1,
    minutes: 18,
    objectives: [
      "理解为什么必须啃下英文",
      "记住最高频的数据中心英文缩写",
      "学会读英文设备铭牌与文档的基本套路",
    ],
    blocks: [
      { type: "h2", text: "为什么绕不开英语" },
      { type: "p", text: "数据中心是全球化行业：核心标准（TIA-942、Uptime Tier）、主流厂商文档（Cisco、Schneider、Vertiv）、含金量高的认证考试，**很多只有英文或以英文为准**。你不需要口语流利，但要能**读懂技术文档、看懂设备铭牌、应对英文考题**。" },
      { type: "callout", variant: "tip", title: "目标定位", body: "专业英语是“阅读型”技能：认识专业词 + 看懂缩写 + 读懂句子结构即可。词汇是关键，且数据中心高频词其实就那几百个，学起来很快。" },
      { type: "h2", text: "必背高频缩写" },
      { type: "table", headers: ["缩写", "全称", "中文"], rows: [
        ["DC", "Data Center", "数据中心"],
        ["UPS", "Uninterruptible Power Supply", "不间断电源"],
        ["PDU", "Power Distribution Unit", "电源分配单元"],
        ["ATS", "Automatic Transfer Switch", "自动转换开关"],
        ["CRAC", "Computer Room Air Conditioner", "机房精密空调（直膨式）"],
        ["CRAH", "Computer Room Air Handler", "机房空气处理机组（冷冻水式）"],
        ["PUE", "Power Usage Effectiveness", "电能使用效率"],
        ["HVAC", "Heating, Ventilation, Air Conditioning", "暖通空调"],
        ["SLA", "Service Level Agreement", "服务等级协议"],
        ["DCIM", "Data Center Infrastructure Management", "数据中心基础设施管理"],
        ["ToR", "Top of Rack", "机柜顶部（交换机布放方式）"],
        ["RU / U", "Rack Unit", "机架单元（1U≈4.45cm 高）"],
      ] },
      { type: "knowledge", discipline: "英语", title: "技巧：缩写怎么记", body: "别死背字母，记“全称里每个词的意思”。比如 UPS = Uninterruptible(不间断) Power(电源) Supply(供给)，连起来自然就懂。读全称三遍，缩写就记住了。" },
      { type: "h2", text: "读懂设备铭牌" },
      { type: "p", text: "设备上的英文铭牌（nameplate）信息高度套路化，认识这些词就能读懂关键参数：" },
      { type: "table", headers: ["英文", "含义"], rows: [
        ["Input / Output", "输入 / 输出"],
        ["Voltage (V)", "电压（伏）"],
        ["Current / Amps (A)", "电流（安）"],
        ["Power (W / kW)", "功率（瓦 / 千瓦）"],
        ["Frequency (Hz)", "频率（赫兹），中国 50Hz"],
        ["Rated / Max", "额定 / 最大"],
        ["Load", "负载"],
        ["Phase (1P / 3P)", "相数（单相 / 三相）"],
      ] },
      { type: "callout", variant: "info", title: "全站术语表", body: "本站内置可搜索的中英术语表（导航栏“术语表”）。学习中遇到生词，随手一查即可，长期积累就成了你的专业词汇库。" },
    ],
    quiz: [
      { id: "0-2-q1", kind: "single", question: "PUE 的全称与含义是？",
        options: ["Power Usage Effectiveness，电能使用效率", "Public Utility Energy，公共能源", "Peak Usage Estimate，峰值用量估计", "Power Unit Efficiency，电源单元效率"],
        answer: [0], explanation: "PUE = Power Usage Effectiveness，衡量数据中心电能利用效率的核心指标，越接近 1 越好。" },
      { id: "0-2-q2", kind: "single", question: "CRAC 和 CRAH 的主要区别是？",
        options: ["一个制冷一个制热", "CRAC 直膨式、CRAH 用冷冻水", "没有区别", "一个室内一个室外"],
        answer: [1], explanation: "CRAC 是直接膨胀（自带压缩机制冷），CRAH 用冷冻水盘管换热，二者都是机房空调。" },
      { id: "0-2-q3", kind: "single", question: "设备铭牌上的 “3P / 50Hz” 表示？",
        options: ["3 个端口、50 个", "三相电、频率 50 赫兹", "3 级保护、50 度", "3 瓦、50 安"],
        answer: [1], explanation: "P=Phase 相，3P 即三相；Hz=Frequency 频率，中国电网为 50Hz。" },
    ],
    flashcards: [
      { id: "0-2-f1", front: "UPS 全称与中文", back: "Uninterruptible Power Supply，不间断电源。", chapterId: "0-2" },
      { id: "0-2-f2", front: "PUE 是什么", back: "Power Usage Effectiveness，电能使用效率，越接近 1 越节能。", chapterId: "0-2" },
      { id: "0-2-f3", front: "1U 有多高", back: "1 Rack Unit ≈ 4.45 cm（1.75 英寸）。", chapterId: "0-2" },
      { id: "0-2-f4", front: "CRAC vs CRAH", back: "CRAC 直膨式自带压缩机；CRAH 用冷冻水盘管。", chapterId: "0-2" },
    ],
  },

  // ----------------------------------------------------------
  {
    id: "0-3",
    part: 0,
    index: "0.3",
    title: "必备数学",
    summary: "只学数据中心要用到的数学：单位换算、公式变形、百分比、对数。",
    tier: 1,
    minutes: 22,
    objectives: [
      "熟练做单位与数量级换算（k/M/G、kW/kVA 等）",
      "会把公式变形求任意一个未知量",
      "理解百分比、比例与可用性“几个 9”",
    ],
    blocks: [
      { type: "h2", text: "数量级与单位前缀" },
      { type: "p", text: "数据中心里到处是 k（千）、M（兆/百万）、G（吉/十亿）。先把前缀和换算搞熟，后面看功率、容量、带宽才不晕。" },
      { type: "table", headers: ["前缀", "符号", "倍数", "例子"], rows: [
        ["千 kilo", "k", "10³ = 1,000", "1 kW = 1000 W"],
        ["兆 mega", "M", "10⁶", "1 MW = 1000 kW"],
        ["吉 giga", "G", "10⁹", "1 Gbps 网速"],
        ["太 tera", "T", "10¹²", "1 TB 硬盘"],
        ["毫 milli", "m", "10⁻³", "1 mA = 0.001 A"],
      ] },
      { type: "widget", widget: "data-units", title: "动手试试：数据单位换算器" },
      { type: "knowledge", discipline: "数学", title: "比特 bit 与字节 byte 别混", body: "网速常用 bit（小写 b，bps），存储常用 Byte（大写 B）。1 Byte = 8 bit。所以 100 Mbps 的带宽，理论最大下载约 100÷8 = 12.5 MB/s。" },
      { type: "h2", text: "公式变形：会求任意未知量" },
      { type: "p", text: "工程里最常用的就是“知道两个量、求第三个”。以最经典的功率公式为例：" },
      { type: "callout", variant: "key", title: "P = U × I", body: "功率 = 电压 × 电流。变形：求电流 I = P ÷ U；求电压 U = P ÷ I。记住三角形口诀：盖住要求的量，剩下两个的关系就是算式。" },
      { type: "p", text: "举例：一台服务器 230V、工作电流 2A，功率 = 230 × 2 = 460 W。若已知功率 460W、电压 230V，求电流 = 460 ÷ 230 = 2A。" },
      { type: "widget", widget: "ohm", title: "动手试试：欧姆/功率计算器" },
      { type: "h2", text: "百分比、比例与“几个 9”" },
      { type: "p", text: "可用性（Availability）用百分比表示，业内常说“几个 9”。它直接关系到一年允许宕机多久：" },
      { type: "table", headers: ["可用性", "说法", "每年允许宕机"], rows: [
        ["99%", "两个 9", "约 3.65 天"],
        ["99.9%", "三个 9", "约 8.77 小时"],
        ["99.99%", "四个 9", "约 52.6 分钟"],
        ["99.999%", "五个 9", "约 5.26 分钟"],
      ] },
      { type: "knowledge", discipline: "数学", title: "怎么算允许宕机时间", body: "一年 = 8760 小时。允许宕机 = 8760 ×（1 − 可用性）。例：99.9% → 8760 × 0.001 = 8.76 小时。多一个 9，宕机时间就少一个数量级。" },
      { type: "callout", variant: "tip", title: "kW 和 kVA 的关系", body: "kW 是“真正干活的”有功功率，kVA 是“视在功率”。kW = kVA × 功率因数(PF)。机房设备 PF 通常 0.9 左右。买 UPS 看 kVA，算实际带载看 kW。后面电工章会细讲。" },
    ],
    quiz: [
      { id: "0-3-q1", kind: "single", question: "100 Mbps 带宽，理论最大下载速度约为？",
        options: ["100 MB/s", "12.5 MB/s", "800 MB/s", "10 MB/s"],
        answer: [1], explanation: "1 Byte=8 bit，100 Mbps ÷ 8 = 12.5 MB/s。bit 与 Byte 务必区分。" },
      { id: "0-3-q2", kind: "single", question: "服务器 230V、电流 2A，功率是多少？",
        options: ["115 W", "232 W", "460 W", "0.115 W"],
        answer: [2], explanation: "P = U × I = 230 × 2 = 460 W。" },
      { id: "0-3-q3", kind: "single", question: "可用性 99.99%（四个 9）每年大约允许宕机？",
        options: ["8.77 小时", "52.6 分钟", "5.26 分钟", "3.65 天"],
        answer: [1], explanation: "8760 ×（1−0.9999）= 0.876 小时 ≈ 52.6 分钟。" },
      { id: "0-3-q4", kind: "single", question: "kW 与 kVA 的关系是？",
        options: ["完全相等", "kW = kVA × 功率因数", "kVA = kW × 频率", "没有关系"],
        answer: [1], explanation: "kW（有功）= kVA（视在）× 功率因数 PF。机房 PF 常取约 0.9。" },
    ],
    flashcards: [
      { id: "0-3-f1", front: "1 Byte = 多少 bit？", back: "8 bit。网速用 bit(b)，存储用 Byte(B)。", chapterId: "0-3" },
      { id: "0-3-f2", front: "功率公式及变形", back: "P=U×I；I=P÷U；U=P÷I。", chapterId: "0-3" },
      { id: "0-3-f3", front: "一年允许宕机怎么算", back: "8760 小时 ×（1 − 可用性）。", chapterId: "0-3" },
      { id: "0-3-f4", front: "kW 与 kVA", back: "kW = kVA × 功率因数(PF)。", chapterId: "0-3" },
    ],
  },

  // ----------------------------------------------------------
  {
    id: "0-4",
    part: 0,
    index: "0.4",
    title: "必备物理",
    summary: "撑起电工与暖通的物理：电与磁、热与传热、流体与光。",
    tier: 1,
    minutes: 24,
    objectives: [
      "建立电压/电流/电阻的直观理解",
      "理解热量、温度、传热三种方式",
      "了解气流与光纤背后的物理",
    ],
    blocks: [
      { type: "h2", text: "电：用“水管”来理解" },
      { type: "p", text: "电看不见摸不着，但可以用水来类比，瞬间变直观：" },
      { type: "table", headers: ["电学量", "水管类比", "单位"], rows: [
        ["电压 U（电位差）", "水压（水位高低差）", "伏特 V"],
        ["电流 I", "水流量（每秒流过多少水）", "安培 A"],
        ["电阻 R", "管子粗细（越细越阻碍）", "欧姆 Ω"],
        ["功率 P", "水流做功的快慢", "瓦特 W"],
      ] },
      { type: "callout", variant: "key", title: "欧姆定律 U = I × R", body: "电压 = 电流 × 电阻。水压越高、管子越粗（电阻越小），水流（电流）越大。这是所有电学的基石。" },
      { type: "knowledge", discipline: "物理", title: "直流 DC 与交流 AC", body: "DC（直流）电流方向不变，如电池、服务器内部。AC（交流）方向周期性改变，如市电（中国 50Hz，即每秒变向 50 个周期）。数据中心从市电(AC)进来，最终给芯片用的是 DC，中间要经过多次转换。" },
      { type: "h2", text: "电与磁：发电和变压的秘密" },
      { type: "p", text: "电与磁是一体两面：**电流produces磁场，变化的磁场produces电流**。发电机靠这个原理把机械能变电能；变压器靠它升降电压；电动机靠它把电变成转动。机房里的发电机、变压器、风机电机，本质都是电磁现象。" },
      { type: "h2", text: "热：数据中心的头号敌人" },
      { type: "p", text: "服务器耗的电几乎全部变成热。**用多少电，就产生多少热，必须等量地搬走**，否则设备过热宕机。这就是为什么数据中心一半的功夫花在制冷上。" },
      { type: "callout", variant: "info", title: "温度 ≠ 热量", body: "温度是“冷热程度”（℃），热量是“能量多少”（焦耳 J 或瓦时）。一杯开水温度高但热量少，一池温水温度低但热量大。制冷要搬走的是“热量”。" },
      { type: "table", headers: ["传热方式", "原理", "机房例子"], rows: [
        ["传导 Conduction", "通过接触直接传", "芯片热量传到散热片"],
        ["对流 Convection", "靠流动的空气/液体带走", "风扇吹风带走热量"],
        ["辐射 Radiation", "以电磁波形式发射", "设备表面散热（占比小）"],
      ] },
      { type: "knowledge", discipline: "物理", title: "为什么液冷越来越火", body: "水带走热量的能力约是空气的 3000 多倍（按体积比热）。芯片功率越来越高，风冷搬不动那么多热，于是液冷（直接用液体贴近芯片散热）成为高功率机柜的趋势。" },
      { type: "h2", text: "气流与光（极简）" },
      { type: "list", items: [
        "**气流**：空气和水一样会“走阻力最小的路”。机房制冷的核心就是组织气流，让冷风精准送到服务器进风口——后面暖通章详讲冷热通道。",
        "**光纤里的全反射**：光在玻璃纤维里不断“全反射”前进，几乎不损耗，所以能高速远距离传数据。信号强弱用 dB（分贝）衡量，后面通信章会讲。",
      ] },
    ],
    quiz: [
      { id: "0-4-q1", kind: "single", question: "用水管类比，电压相当于？",
        options: ["水流量", "水压（水位差）", "管子粗细", "水温"],
        answer: [1], explanation: "电压≈水压，电流≈水流量，电阻≈管子粗细。" },
      { id: "0-4-q2", kind: "single", question: "欧姆定律的表达式是？",
        options: ["U = I × R", "P = U + I", "R = U × I", "I = U × R"],
        answer: [0], explanation: "U = I × R，电压等于电流乘电阻。" },
      { id: "0-4-q3", kind: "single", question: "关于服务器发热，正确的是？",
        options: ["耗电越多发热越少", "耗多少电就产生多少热，必须等量搬走", "服务器基本不发热", "发热靠自然散掉即可"],
        answer: [1], explanation: "电能几乎全部转为热能，必须由制冷系统等量带走，否则过热宕机。" },
      { id: "0-4-q4", kind: "single", question: "风扇吹风带走热量属于哪种传热？",
        options: ["传导", "对流", "辐射", "蒸发"],
        answer: [1], explanation: "靠流动的空气带走热量属于对流。" },
    ],
    flashcards: [
      { id: "0-4-f1", front: "欧姆定律", back: "U = I × R（电压=电流×电阻）。", chapterId: "0-4" },
      { id: "0-4-f2", front: "AC 与 DC", back: "AC 交流，方向周期变化（市电50Hz）；DC 直流，方向不变（电池、芯片）。", chapterId: "0-4" },
      { id: "0-4-f3", front: "三种传热方式", back: "传导、对流、辐射。", chapterId: "0-4" },
      { id: "0-4-f4", front: "温度 vs 热量", back: "温度是冷热程度(℃)，热量是能量多少(J)；制冷搬走的是热量。", chapterId: "0-4" },
    ],
  },

  // ----------------------------------------------------------
  {
    id: "0-5",
    part: 0,
    index: "0.5",
    title: "计算机基础",
    summary: "二进制与数据单位、计算机五大部件、操作系统与网络协议栈。",
    tier: 1,
    minutes: 24,
    objectives: [
      "理解二进制与数据单位（bit/Byte/KB…）",
      "说清计算机五大组成部件",
      "建立 OSI / TCP-IP 网络分层的初步认识",
    ],
    blocks: [
      { type: "h2", text: "为什么是二进制" },
      { type: "p", text: "计算机内部只认两种状态：通电/断电、高电平/低电平——记作 1 和 0。一个 0 或 1 就是 1 个 **bit（比特）**。8 个 bit 组成 1 个 **Byte（字节）**，这是数据的基本计量单位。" },
      { type: "table", headers: ["单位", "等于", "大致感受"], rows: [
        ["1 Byte (B)", "8 bit", "一个英文字符"],
        ["1 KB", "1024 B", "一小段文字"],
        ["1 MB", "1024 KB", "一张照片"],
        ["1 GB", "1024 MB", "一部标清电影"],
        ["1 TB", "1024 GB", "一块大硬盘"],
        ["1 PB", "1024 TB", "大型数据中心级别"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "为什么硬盘“缩水”", body: "厂商按 1000 进制标容量（1TB=10¹²字节），系统按 1024 进制显示，所以“1TB 硬盘”在电脑里只显示约 931GB，并非缺斤少两。" },
      { type: "h2", text: "计算机五大组成" },
      { type: "p", text: "无论手机、服务器还是超算，都由这五部分组成。服务器只是“更强、更耐用、为 7×24 运行而生”的计算机。" },
      { type: "table", headers: ["部件", "作用", "类比"], rows: [
        ["CPU（运算器+控制器）", "计算与指挥", "大脑"],
        ["内存 RAM", "临时高速存放正在用的数据", "桌面"],
        ["存储（硬盘/SSD）", "长期保存数据", "书柜"],
        ["输入设备", "录入信息", "眼睛耳朵"],
        ["输出设备", "呈现结果", "嘴巴"],
      ] },
      { type: "callout", variant: "info", title: "内存 vs 硬盘", body: "内存快但断电即失（临时），硬盘慢但断电保留（长期）。这就是关机前要“保存”的原因——把内存里的成果写进硬盘。" },
      { type: "h2", text: "操作系统与 Linux" },
      { type: "p", text: "操作系统（OS）是管理硬件、运行程序的“总管”。数据中心服务器**绝大多数跑 Linux**——稳定、免费、适合远程管理。学一点 Linux 命令行是 IT 方向的必备技能（后面 IT 部分会带你入门）。" },
      { type: "h2", text: "网络分层：OSI 与 TCP/IP" },
      { type: "p", text: "数据在网络里传输，被拆成一层层处理，像寄快递时层层打包。这套分层模型是理解网络的钥匙。" },
      { type: "table", headers: ["TCP/IP 层", "干什么", "例子"], rows: [
        ["应用层", "你直接用的服务", "网页 HTTP、邮件"],
        ["传输层", "保证数据可靠送达", "TCP / UDP、端口"],
        ["网络层", "找路、跨网络寻址", "IP 地址、路由器"],
        ["网络接口层", "同一网络内实际收发", "网卡、MAC、交换机"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "IP 地址是什么", body: "IP 地址是设备在网络中的“门牌号”，如 192.168.1.10。数据靠 IP 找到目标设备，靠端口号找到目标程序。后面网络章会系统讲。" },
    ],
    quiz: [
      { id: "0-5-q1", kind: "single", question: "1 Byte 等于多少 bit？",
        options: ["4", "8", "16", "1024"], answer: [1],
        explanation: "1 Byte = 8 bit，这是数据计量的基础。" },
      { id: "0-5-q2", kind: "single", question: "关于内存(RAM)和硬盘，正确的是？",
        options: ["内存断电数据保留", "硬盘比内存快", "内存快但断电即失，硬盘慢但能长期保存", "两者完全一样"],
        answer: [2], explanation: "内存临时高速、断电丢失；硬盘长期保存、相对慢。" },
      { id: "0-5-q3", kind: "single", question: "数据中心服务器最常用的操作系统是？",
        options: ["Windows 家庭版", "Linux", "iOS", "Android"],
        answer: [1], explanation: "Linux 稳定、免费、便于远程管理，是服务器主流。" },
      { id: "0-5-q4", kind: "single", question: "IP 地址的作用类似于？",
        options: ["程序的名字", "设备在网络中的门牌号", "硬盘容量", "电源电压"],
        answer: [1], explanation: "IP 是设备在网络中的地址（门牌号），端口号则定位具体程序。" },
    ],
    flashcards: [
      { id: "0-5-f1", front: "bit 与 Byte", back: "1 Byte = 8 bit。bit 是最小单位（0/1）。", chapterId: "0-5" },
      { id: "0-5-f2", front: "计算机五大组成", back: "CPU、内存、存储、输入、输出。", chapterId: "0-5" },
      { id: "0-5-f3", front: "内存 vs 硬盘", back: "内存快、断电丢失；硬盘慢、长期保存。", chapterId: "0-5" },
      { id: "0-5-f4", front: "TCP/IP 四层", back: "应用层、传输层、网络层、网络接口层。", chapterId: "0-5" },
    ],
  },

  // ----------------------------------------------------------
  {
    id: "0-6",
    part: 0,
    index: "0.6",
    title: "通信基础",
    summary: "信号与带宽、模拟与数字、传输介质、光通信与衰减(dB)。",
    tier: 1,
    minutes: 18,
    objectives: [
      "理解带宽、速率与延迟的区别",
      "分清铜缆与光纤的特点与适用",
      "初步理解 dB（分贝）表示信号强弱",
    ],
    blocks: [
      { type: "h2", text: "通信在数据中心的位置" },
      { type: "p", text: "数据中心存在的意义就是“联网提供服务”。服务器之间、机柜之间、数据中心与外界之间，全靠通信链路连接。理解通信，才能看懂网络与布线两大主题。" },
      { type: "h2", text: "带宽、速率与延迟" },
      { type: "table", headers: ["概念", "含义", "类比（高速公路）"], rows: [
        ["带宽 Bandwidth", "通道最大容量（bps）", "车道数量"],
        ["速率 Throughput", "实际传输速度", "实际车流量"],
        ["延迟 Latency", "数据从 A 到 B 的耗时", "跑完全程要多久"],
      ] },
      { type: "callout", variant: "info", title: "带宽大 ≠ 延迟低", body: "带宽是“一次能传多少”，延迟是“传过去要多久”。下载大文件看带宽，打游戏/打电话看延迟。两者都重要但不是一回事。" },
      { type: "h2", text: "模拟信号与数字信号" },
      { type: "p", text: "**模拟信号**连续变化（如声波）；**数字信号**只有 0/1 两种状态。数字信号抗干扰强、易处理、能精确复制，是现代通信与计算机的基础。把模拟（如语音）变成数字叫“数字化”。" },
      { type: "h2", text: "传输介质：铜缆 vs 光纤" },
      { type: "table", headers: ["对比", "铜缆（网线）", "光纤"], rows: [
        ["传输", "电信号", "光信号"],
        ["距离", "短（百米级）", "远（千米~更长）"],
        ["速率", "较高", "极高"],
        ["抗干扰", "易受电磁干扰", "不受电磁干扰"],
        ["成本", "便宜、易施工", "较贵、需专业熔接"],
        ["机房用途", "机柜内/近距离", "机柜间/跨楼/长距离骨干"],
      ] },
      { type: "knowledge", discipline: "通信", title: "光纤为什么快又远", body: "光在玻璃纤芯里靠“全反射”几乎无损耗地前进，不受电磁干扰，所以能高速、长距离传输。数据中心骨干和高速互联大量用光纤。" },
      { type: "h2", text: "用 dB 表示信号强弱" },
      { type: "p", text: "信号在传输中会衰减（变弱）。工程上用 **dB（分贝）** 这种“对数刻度”来表示倍数关系，因为信号强弱跨越很多数量级，用对数更方便。" },
      { type: "knowledge", discipline: "数学", title: "dB 的直观感受", body: "每 +3dB 约等于功率翻倍，每 +10dB 约等于 10 倍。负数表示衰减：−3dB 约剩一半。布线时会有“链路损耗预算”，确保信号到对端还够强。" },
      { type: "callout", variant: "tip", title: "承上启下", body: "这些通信概念会在第 4 部分“综合布线”和第 5 部分“数据中心网络”里反复用到。现在有个印象即可，到时回头看会更清楚。" },
    ],
    quiz: [
      { id: "0-6-q1", kind: "single", question: "下列哪个描述的是“延迟”？",
        options: ["通道最大容量", "数据从 A 到 B 所需的时间", "硬盘容量", "电压高低"],
        answer: [1], explanation: "延迟=数据传输耗时；带宽=通道容量，二者不同。" },
      { id: "0-6-q2", kind: "single", question: "相比铜缆，光纤的优势不包括？",
        options: ["传输距离远", "不受电磁干扰", "速率极高", "成本最低、施工最简单"],
        answer: [3], explanation: "光纤更贵、需专业熔接，成本与施工不是它的优势。" },
      { id: "0-6-q3", kind: "single", question: "数字信号相比模拟信号的优点是？",
        options: ["更容易受干扰", "抗干扰强、易处理、可精确复制", "只能短距离", "不能数字化语音"],
        answer: [1], explanation: "数字信号只有 0/1，抗干扰、易处理、可无损复制。" },
      { id: "0-6-q4", kind: "single", question: "信号 +10dB 大约意味着功率变为原来的？",
        options: ["2 倍", "10 倍", "一半", "不变"],
        answer: [1], explanation: "+10dB≈10 倍，+3dB≈2 倍；dB 是对数刻度。" },
    ],
    flashcards: [
      { id: "0-6-f1", front: "带宽 vs 延迟", back: "带宽=通道容量（一次能传多少）；延迟=传输耗时（要多久）。", chapterId: "0-6" },
      { id: "0-6-f2", front: "铜缆 vs 光纤", back: "铜缆近距离便宜、传电信号；光纤远距离高速、传光、不受干扰。", chapterId: "0-6" },
      { id: "0-6-f3", front: "dB 直观", back: "+3dB≈翻倍，+10dB≈10倍，负数表示衰减。", chapterId: "0-6" },
    ],
  },
];
