import { Tier } from "@/lib/types";

export const TIERS: Tier[] = [
  {
    level: 1,
    badge: "🥉",
    name: "数据中心通识者",
    title: "DC Apprentice",
    goal: "建立全景认知，听懂行话，搞清楚数据中心是什么、有哪些角色。",
    parts: [0, 1],
    knowledge: "基础垫脚石 + 入门与全景（第0、1部分）",
    practice: ["组件识别配对", "“一个请求的旅程”路径追踪", "数据中心类型辨识", "数据单位换算"],
    certs: "具备进入行业的基础常识",
    unlock: ["完成第0、1部分全部章节", "各章自测 ≥ 80%", "完成入门情景练习"],
  },
  {
    level: 2,
    badge: "🥈",
    name: "设施基础工",
    title: "Facilities Foundation",
    goal: "搞懂数据中心的“身体”：供电、制冷、布线，掌握电工与暖通基本功。",
    parts: [2, 3, 4],
    knowledge: "电工 + 暖通 + 物理基础设施（第2、3、4部分）",
    practice: ["电力链路搭建", "UPS 电池续航计算", "PUE 计算", "制冷量估算", "冷热通道拖拽规划", "机柜 U 位上架", "N+1/2N 冗余推演", "LOTO 上锁挂牌演练"],
    certs: "≈ EPI CDCP 设施知识水平（打底证）",
    unlock: ["完成第2、3、4部分全部章节", "完成全部供电/制冷实操", "通过段位模拟考 ≥ 70%"],
  },
  {
    level: 3,
    badge: "🥇",
    name: "IT 基础设施工程师",
    title: "IT Infrastructure",
    goal: "掌握数据中心的“大脑”：服务器、存储、网络与虚拟化。",
    parts: [5],
    knowledge: "IT 基础设施（第5部分）",
    practice: ["机柜上架布局", "RAID 配置模拟", "引导实验：Packet Tracer 搭脊叶拓扑", "引导实验：VirtualBox 建虚拟机"],
    certs: "≈ CompTIA Server+ / Network+，打下 CCNA 实操基础",
    unlock: ["完成第5部分全部章节", "完成至少 2 个引导实验", "通过段位模拟考 ≥ 70%"],
  },
  {
    level: 4,
    badge: "🏅",
    name: "运维与可靠性专员",
    title: "Operations & Reliability",
    goal: "会管理、会算可用性、会按规程处理故障。",
    parts: [6],
    knowledge: "运营与可靠性（第6部分）",
    practice: ["DCIM 仪表盘判读", "可用性 / SLA 计算", "故障排查决策树（MOP/EOP）", "巡检与变更演练"],
    certs: "≈ EPI CDCS / 运维岗位能力",
    unlock: ["完成第6部分全部章节", "完成故障排查情景练习", "通过段位模拟考 ≥ 70%"],
  },
  {
    level: 5,
    badge: "🎖️",
    name: "数据中心综合工程师",
    title: "Integrated Professional",
    goal: "能把各系统串起来做整体判断与设计。",
    parts: [7],
    knowledge: "安全 · 标准 · 职业 + 综合复盘（第7部分）",
    practice: ["毕业大项目：设计一座达标 Tier 的小型数据中心", "全真模拟考（对齐 CDCE）"],
    certs: "≈ EPI CDCE 综合水平，可上岗",
    unlock: ["完成第7部分全部章节", "完成毕业大项目", "通过全真模拟考 ≥ 75%"],
  },
  {
    level: 6,
    badge: "👑",
    name: "专精分支",
    title: "Expert / Specialization",
    goal: "在设施 / 网络 / 系统某一方向走深，冲击高阶认证。",
    parts: [],
    knowledge: "三条分支任选其一深耕",
    practice: ["设施深耕 → Uptime ATD", "网络深耕 → Cisco CCNP DC（高阶模拟器）", "系统/云深耕 → VMware VCP / AWS·Azure"],
    certs: "高阶专项认证",
    unlock: ["选定一条分支", "完成该分支高阶实验项目", "通过对应方向题库 ≥ 80%"],
  },
];

export function tierByLevel(level: number) {
  return TIERS.find((t) => t.level === level);
}
