import { Chapter } from "@/lib/types";

export const PART5: Chapter[] = [
  // ---------------------- 第 23 章 ----------------------
  {
    id: "5-23",
    part: 5,
    index: "23",
    title: "服务器与计算硬件",
    summary: "服务器解剖、机架式/刀片/整机柜，以及与PC的区别。",
    tier: 3,
    minutes: 24,
    objectives: [
      "认识服务器主要部件",
      "区分机架式/刀片/整机柜/GPU 服务器",
      "理解服务器为何强调冗余与远程管理",
    ],
    blocks: [
      { type: "h2", text: "服务器：为不停机而生的电脑" },
      { type: "p", text: "服务器本质是高性能、高可靠、为 7×24 连续运行设计的计算机。它和家用 PC 的部件类似，但处处为“稳定、可维护、可远程管理”做了强化。" },
      { type: "table", headers: ["部件", "作用", "服务器特点"], rows: [
        ["CPU", "计算核心", "多路、多核，算力强"],
        ["内存 RAM", "高速临时存储", "容量大，带 ECC 纠错"],
        ["硬盘/SSD", "数据存储", "可热插拔、常配 RAID"],
        ["主板", "连接各部件", "支持多路CPU、大内存"],
        ["电源 PSU", "供电", "冗余双电源、可热插拔"],
        ["网卡 NIC", "联网", "多口、高速(10/25/100G)"],
        ["BMC", "带外管理芯片", "远程开关机、监控、装系统"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "BMC / IPMI / iLO / iDRAC", body: "服务器有个独立的“带外管理”模块(BMC)，即使主系统关机也能通过网络远程开关机、看硬件状态、远程装系统。各家叫法不同：HPE 叫 iLO、戴尔叫 iDRAC，通用协议是 IPMI/Redfish。运维不用跑机房就是靠它。" },
      { type: "h2", text: "服务器的外形规格" },
      { type: "table", headers: ["类型", "说明", "适合"], rows: [
        ["机架式 Rack", "1U/2U/4U 装入标准机柜，最常见", "通用，灵活"],
        ["刀片 Blade", "多个刀片插入共享机箱，共用电源/散热", "高密度、统一管理"],
        ["整机柜 Rack-scale", "整柜出厂预集成，到场即用", "超大规模快速部署"],
        ["GPU 服务器", "搭载多块 GPU，功率高", "AI/高性能计算"],
      ] },
      { type: "callout", variant: "key", title: "为什么服务器到处是“冗余+热插拔”", body: "数据中心要求不停机。所以电源双路冗余、硬盘 RAID、风扇冗余，且都能“热插拔”——坏了不关机就能换。这是服务器区别于 PC 的核心理念，呼应前面学的“消除单点故障”。" },
      { type: "h2", text: "选型看什么" },
      { type: "list", items: [
        "**算力**：CPU 路数/核数、是否需要 GPU；",
        "**内存**：容量与是否 ECC；",
        "**存储**：容量、性能(SSD/NVMe)、RAID；",
        "**网络**：网口数量与速率；",
        "**可靠性**：冗余电源、远程管理、保修服务。",
      ] },
    ],
    quiz: [
      { id: "5-23-q1", kind: "single", question: "服务器区别于家用 PC 的核心理念是？",
        options: ["更便宜", "为不停机而生：冗余、热插拔、远程管理", "没有 CPU", "不能联网"], answer: [1],
        explanation: "服务器强调高可靠：冗余电源/RAID/风扇、热插拔、带外管理。" },
      { id: "5-23-q2", kind: "single", question: "BMC（如 iLO/iDRAC）的作用是？",
        options: ["制冷", "即使关机也能远程开关机/监控/装系统", "供电", "存数据"], answer: [1],
        explanation: "BMC 提供带外管理，运维无需到现场即可远程操作硬件。" },
      { id: "5-23-q3", kind: "single", question: "AI/高性能计算最可能用哪类服务器？",
        options: ["普通 1U 机架式", "GPU 服务器", "刀片管理机", "瘦客户端"], answer: [1],
        explanation: "AI/HPC 依赖大量并行算力，常用搭载多 GPU 的服务器。" },
      { id: "5-23-q4", kind: "single", question: "服务器内存常用 ECC 是为了？",
        options: ["更便宜", "自动纠正内存错误，提升可靠性", "提高容量上限到无限", "降低功耗为零"], answer: [1],
        explanation: "ECC 内存能检测并纠正错误，保障长期运行的稳定。" },
    ],
    flashcards: [
      { id: "5-23-f1", front: "服务器核心理念", back: "为不停机而生：冗余电源/RAID/风扇、热插拔、远程管理。", chapterId: "5-23" },
      { id: "5-23-f2", front: "BMC/IPMI", back: "带外管理：关机也能远程开关机/监控/装系统(iLO/iDRAC)。", chapterId: "5-23" },
      { id: "5-23-f3", front: "服务器外形", back: "机架式(1U/2U)、刀片、整机柜、GPU服务器。", chapterId: "5-23" },
    ],
  },

  // ---------------------- 第 24 章 ----------------------
  {
    id: "5-24",
    part: 5,
    index: "24",
    title: "存储系统",
    summary: "HDD/SSD、DAS/NAS/SAN 与 RAID 基础。",
    tier: 3,
    minutes: 24,
    objectives: [
      "区分 HDD 与 SSD 及接口",
      "理解 DAS/NAS/SAN 的差异",
      "掌握常见 RAID 级别的取舍",
    ],
    blocks: [
      { type: "h2", text: "硬盘：HDD 与 SSD" },
      { type: "table", headers: ["", "HDD 机械硬盘", "SSD 固态硬盘"], rows: [
        ["原理", "磁盘旋转+磁头读写", "闪存芯片，无机械部件"],
        ["速度", "慢", "快(尤其随机读写)"],
        ["容量/价格", "大容量便宜", "较贵(但持续下降)"],
        ["可靠/功耗", "怕震动、功耗较高", "抗震、功耗低"],
        ["用途", "冷数据、大容量备份", "热数据、系统盘、数据库"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "接口：SATA / SAS / NVMe", body: "SATA 常见、廉价、速度一般；SAS 企业级、可靠性高、支持更多盘；NVMe 走 PCIe 总线，速度最快，用于高性能 SSD。性能排序大致 NVMe > SAS > SATA。" },
      { type: "h2", text: "存储怎么连：DAS / NAS / SAN" },
      { type: "table", headers: ["类型", "全称/方式", "特点"], rows: [
        ["DAS", "直连存储", "硬盘直接接在服务器上，简单但难共享"],
        ["NAS", "网络附加存储", "通过以太网共享“文件”，即插即用的文件服务器"],
        ["SAN", "存储区域网络", "专用高速网络提供“块”存储，性能高，企业核心"],
      ] },
      { type: "callout", variant: "info", title: "块 / 文件 / 对象存储", body: "块存储(像裸硬盘,SAN)性能高、给数据库/虚拟机用；文件存储(NAS)按文件夹共享、好理解；对象存储(如 S3)按对象+元数据海量扩展、适合云和非结构化数据。" },
      { type: "h2", text: "RAID：用多块盘换可靠与性能" },
      { type: "p", text: "**RAID** 把多块硬盘组合，提升性能和/或冗余。坏一块盘数据不丢，是企业存储的基本功。" },
      { type: "table", headers: ["级别", "做法", "特点", "容错"], rows: [
        ["RAID 0", "条带，数据分散写多盘", "速度快、无冗余", "坏1块全丢 ❌"],
        ["RAID 1", "镜像，两盘存同样数据", "可靠、容量利用50%", "坏1块仍在 ✅"],
        ["RAID 5", "条带+1份校验", "兼顾性能与容量", "可坏1块 ✅"],
        ["RAID 6", "条带+2份校验", "更安全", "可坏2块 ✅✅"],
        ["RAID 10", "先镜像再条带", "高性能+高可靠", "每组可坏1块 ✅"],
      ] },
      { type: "callout", variant: "key", title: "RAID 不是备份", body: "RAID 防的是“硬盘坏”，但防不了误删、病毒、机房灾难。重要数据仍要做独立备份(最好异地)。这是新人最常见的误区，务必记牢。" },
    ],
    quiz: [
      { id: "5-24-q1", kind: "single", question: "性能最高的 SSD 接口通常是？",
        options: ["SATA", "SAS", "NVMe(PCIe)", "USB"], answer: [2],
        explanation: "NVMe 走 PCIe 总线，速度最快；性能大致 NVMe>SAS>SATA。" },
      { id: "5-24-q2", kind: "single", question: "通过以太网共享“文件”的存储是？",
        options: ["DAS", "NAS", "SAN", "RAID"], answer: [1],
        explanation: "NAS 通过网络共享文件；SAN 提供块存储；DAS 直连。" },
      { id: "5-24-q3", kind: "single", question: "RAID 1 的特点是？",
        options: ["无冗余、最快", "镜像，坏1块数据仍在，容量利用约50%", "可坏2块", "不需要两块盘"], answer: [1],
        explanation: "RAID 1 两盘互为镜像，冗余好但容量利用率约一半。" },
      { id: "5-24-q4", kind: "tf", question: "做了 RAID 就不需要再备份数据了。",
        options: ["正确", "错误"], answer: [1],
        explanation: "RAID 防硬盘故障，但防不了误删/病毒/灾难，仍需独立(异地)备份。" },
    ],
    flashcards: [
      { id: "5-24-f1", front: "HDD vs SSD", back: "HDD大容量便宜较慢；SSD快、抗震、低功耗、较贵。", chapterId: "5-24" },
      { id: "5-24-f2", front: "DAS/NAS/SAN", back: "DAS直连；NAS网络共享文件；SAN专网块存储(企业核心)。", chapterId: "5-24" },
      { id: "5-24-f3", front: "常见RAID", back: "0快无冗余;1镜像;5单校验;6双校验;10镜像+条带。", chapterId: "5-24" },
      { id: "5-24-f4", front: "RAID≠备份", back: "RAID防硬盘坏，防不了误删/灾难，仍需独立异地备份。", chapterId: "5-24" },
    ],
  },

  // ---------------------- 第 25 章 ----------------------
  {
    id: "5-25",
    part: 5,
    index: "25",
    title: "数据中心网络基础",
    summary: "交换与路由、IP/VLAN、防火墙与负载均衡。",
    tier: 3,
    minutes: 26,
    objectives: [
      "区分交换(二层)与路由(三层)",
      "理解 IP、子网与 VLAN",
      "认识防火墙与负载均衡的作用",
    ],
    blocks: [
      { type: "h2", text: "先回顾分层（计算机基础）" },
      { type: "p", text: "数据在网络里分层处理：网络接口层(网卡/交换机/MAC) → 网络层(IP/路由器) → 传输层(TCP/UDP/端口) → 应用层。理解“二层交换、三层路由”就抓住了网络的骨架。" },
      { type: "h2", text: "交换 vs 路由" },
      { type: "table", headers: ["", "交换机 Switch", "路由器 Router"], rows: [
        ["工作层", "二层(数据链路层)", "三层(网络层)"],
        ["依据", "MAC 地址", "IP 地址"],
        ["范围", "同一局域网内转发", "不同网络间寻路"],
        ["类比", "楼内各房间送信", "城市间寄快递找路"],
      ] },
      { type: "knowledge", discipline: "计算机", title: "MAC 与 IP", body: "MAC 是网卡出厂的物理地址(固定)，用于同一网络内定位设备；IP 是逻辑地址(可配置)，用于跨网络寻址。交换看 MAC，路由看 IP，两者配合把数据送到目的地。" },
      { type: "h2", text: "IP、子网与 VLAN" },
      { type: "list", items: [
        "**IP 地址**：设备的网络门牌号（如 10.0.1.20），配合**子网掩码**划分网络范围；",
        "**网关**：本网络通往外部的“门”（常是路由器）；",
        "**VLAN**：在一台交换机上逻辑划分出多个互相隔离的虚拟局域网，把不同业务/租户分开，提升安全与管理性。",
      ] },
      { type: "callout", variant: "info", title: "VLAN 有什么用", body: "同一台物理交换机，可用 VLAN 把财务、研发、来宾网络隔离开，互不干扰、各自广播域更小。数据中心里 VLAN 用来隔离不同业务、客户、用途，是基础且高频的技能。" },
      { type: "h2", text: "关键网络设备" },
      { type: "table", headers: ["设备", "作用"], rows: [
        ["防火墙 Firewall", "按规则放行/拦截流量，安全边界"],
        ["负载均衡 LB", "把请求分摊到多台服务器，提升性能与可用性"],
        ["路由器", "连接不同网络、对外出口"],
        ["交换机", "局域网内高速转发"],
      ] },
      { type: "callout", variant: "key", title: "回到“请求的旅程”", body: "还记得第 1 部分那次请求旅程吗？请求经路由器/防火墙进来，被负载均衡分配，经交换机送到服务器。现在你已经认识这条路上的每个设备了。" },
    ],
    quiz: [
      { id: "5-25-q1", kind: "single", question: "交换机和路由器的主要区别是？",
        options: ["交换机看IP、路由器看MAC", "交换机二层看MAC局域网转发，路由器三层看IP跨网寻路", "完全一样", "路由器只能连一台设备"], answer: [1],
        explanation: "交换=二层(MAC,局域网)；路由=三层(IP,跨网络)。" },
      { id: "5-25-q2", kind: "single", question: "VLAN 的主要作用是？",
        options: ["提高电压", "在交换机上逻辑隔离出多个虚拟局域网", "存储数据", "制冷"], answer: [1],
        explanation: "VLAN 逻辑划分隔离网络，分开不同业务/租户，提升安全与管理。" },
      { id: "5-25-q3", kind: "single", question: "负载均衡器(LB)的作用是？",
        options: ["拦截所有流量", "把请求分摊到多台服务器，提升性能与可用性", "降温", "供电"], answer: [1],
        explanation: "LB 分摊请求避免单台过载，并在某台故障时转移流量。" },
      { id: "5-25-q4", kind: "single", question: "MAC 地址与 IP 地址的关系，正确的是？",
        options: ["都可随意更改", "MAC 物理固定用于本网定位，IP 逻辑可配用于跨网寻址", "MAC 用于跨网", "IP 是物理地址"], answer: [1],
        explanation: "MAC 物理固定(本网)，IP 逻辑可配(跨网)，二者配合送达。" },
    ],
    flashcards: [
      { id: "5-25-f1", front: "交换 vs 路由", back: "交换=二层看MAC(局域网)；路由=三层看IP(跨网络)。", chapterId: "5-25" },
      { id: "5-25-f2", front: "MAC vs IP", back: "MAC物理固定(本网定位)；IP逻辑可配(跨网寻址)。", chapterId: "5-25" },
      { id: "5-25-f3", front: "VLAN作用", back: "在交换机上逻辑隔离出多个虚拟局域网，分隔业务/租户。", chapterId: "5-25" },
      { id: "5-25-f4", front: "防火墙/负载均衡", back: "防火墙按规则放行拦截；LB分摊请求提升性能与可用性。", chapterId: "5-25" },
    ],
  },

  // ---------------------- 第 26 章 ----------------------
  {
    id: "5-26",
    part: 5,
    index: "26",
    title: "数据中心网络架构",
    summary: "传统三层 vs 脊叶、东西/南北向流量与 SDN。",
    tier: 3,
    minutes: 22,
    objectives: [
      "对比传统三层与脊叶(Spine-Leaf)架构",
      "理解东西向与南北向流量",
      "初步认识 SDN 与 Overlay",
    ],
    blocks: [
      { type: "h2", text: "两种流量方向" },
      { type: "table", headers: ["方向", "含义", "例子"], rows: [
        ["南北向 North-South", "数据中心与外部之间的流量", "用户访问网站"],
        ["东西向 East-West", "数据中心内部服务器之间的流量", "微服务/分布式计算互相调用"],
      ] },
      { type: "callout", variant: "info", title: "东西向流量为何暴涨", body: "现代应用是分布式的（微服务、大数据、AI 训练），服务器之间互相大量通信，东西向流量远超南北向。传统网络架构应付不来，催生了脊叶架构。" },
      { type: "h2", text: "传统三层架构" },
      { type: "p", text: "经典的“接入层—汇聚层—核心层”三层树形结构。它为南北向流量设计，东西向流量要绕到上层再下来，路径长、易拥塞、扩展受限。" },
      { type: "h2", text: "脊叶架构(Spine-Leaf)" },
      { type: "p", text: "现代数据中心主流。两层：**Leaf(叶,接入机柜)** 全部连到 **Spine(脊,骨干)**，任意两台服务器之间最多经过“叶-脊-叶”三跳，路径短而一致。" },
      { type: "diagram", svg: `<svg viewBox="0 0 360 150" xmlns="http://www.w3.org/2000/svg" style="width:100%">${[80,200].map(x=>`<rect x="${x}" y="15" width="80" height="28" rx="6" fill="#e3f4f5" stroke="#0e7c86"/><text x="${x+40}" y="33" text-anchor="middle" font-size="11" fill="#15202b">Spine</text>`).join("")}${[30,140,250].map(x=>`<rect x="${x}" y="95" width="70" height="28" rx="6" fill="#dbeafe" stroke="#2563eb"/><text x="${x+35}" y="113" text-anchor="middle" font-size="11" fill="#15202b">Leaf</text>`).join("")}${[80,200].flatMap(sx=>[30,140,250].map(lx=>`<line x1="${sx+40}" y1="43" x2="${lx+35}" y2="95" stroke="#94a3b8" stroke-width="1"/>`)).join("")}<text x="180" y="143" text-anchor="middle" font-size="9" fill="#64748b">每个Leaf连接所有Spine，任意服务器间路径一致</text></svg>`, caption: "脊叶(Spine-Leaf)架构：扁平、等距、易扩展" },
      { type: "list", items: [
        "**优点**：东西向高效、延迟一致、带宽可水平扩展（加 Spine 即可）、无单点；",
        "加机柜就加 Leaf，加带宽就加 Spine，扩展简单。",
      ] },
      { type: "h2", text: "SDN 与 Overlay（了解）" },
      { type: "knowledge", discipline: "计算机", title: "SDN / VXLAN", body: "SDN(软件定义网络)把网络的“控制”与“转发”分离，用软件集中编排网络，灵活自动化。VXLAN 等 Overlay 技术在物理网络之上叠加虚拟网络，让虚拟机/容器可跨物理位置灵活组网——这是云和大规模多租户的基础。先有印象即可。" },
    ],
    quiz: [
      { id: "5-26-q1", kind: "single", question: "服务器之间内部互相通信的流量称为？",
        options: ["南北向", "东西向", "上下向", "内外向"], answer: [1],
        explanation: "东西向=内部服务器之间；南北向=与外部之间。" },
      { id: "5-26-q2", kind: "single", question: "脊叶(Spine-Leaf)架构的优点不包括？",
        options: ["东西向高效、延迟一致", "带宽可水平扩展", "任意服务器间路径一致", "彻底取消所有交换机"], answer: [3],
        explanation: "脊叶仍由 Spine/Leaf 交换机组成，优势是扁平、等距、易扩展。" },
      { id: "5-26-q3", kind: "single", question: "为什么现代数据中心从三层转向脊叶？",
        options: ["为了省交换机", "东西向流量暴涨，三层路径长易拥塞", "脊叶更便宜", "三层不能联网"], answer: [1],
        explanation: "分布式应用使东西向流量激增，脊叶提供短而一致的路径。" },
      { id: "5-26-q4", kind: "single", question: "SDN 的核心思想是？",
        options: ["取消网络", "控制与转发分离，用软件集中编排网络", "只用光纤", "提高电压"], answer: [1],
        explanation: "SDN 分离控制面与转发面，实现集中、灵活、自动化的网络管理。" },
    ],
    flashcards: [
      { id: "5-26-f1", front: "南北向 vs 东西向", back: "南北=与外部；东西=内部服务器之间(现代暴涨)。", chapterId: "5-26" },
      { id: "5-26-f2", front: "脊叶架构", back: "Leaf全连Spine，任意服务器间路径一致，扁平易扩展。", chapterId: "5-26" },
      { id: "5-26-f3", front: "脊叶扩展方式", back: "加机柜=加Leaf；加带宽=加Spine。", chapterId: "5-26" },
      { id: "5-26-f4", front: "SDN", back: "控制与转发分离，软件集中编排网络，灵活自动化。", chapterId: "5-26" },
    ],
  },

  // ---------------------- 第 27 章 ----------------------
  {
    id: "5-27",
    part: 5,
    index: "27",
    title: "虚拟化与云",
    summary: "虚拟化原理、虚拟机 vs 容器、云服务模型。",
    tier: 3,
    minutes: 24,
    objectives: [
      "理解虚拟化与 Hypervisor",
      "区分虚拟机与容器",
      "掌握 IaaS/PaaS/SaaS 与云部署模型",
    ],
    blocks: [
      { type: "h2", text: "虚拟化：一台机器当多台用" },
      { type: "p", text: "**虚拟化**用软件把一台物理服务器切分成多台“虚拟机(VM)”，每台 VM 有自己的操作系统，互相隔离。这样硬件利用率大幅提升，部署也更灵活。" },
      { type: "knowledge", discipline: "计算机", title: "Hypervisor 两类", body: "Hypervisor 是创建和管理 VM 的软件。Type 1(裸金属)直接装在硬件上(如 VMware ESXi、KVM)，性能好、数据中心主流；Type 2 装在操作系统之上(如 VirtualBox)，适合个人测试。" },
      { type: "h2", text: "虚拟机 vs 容器" },
      { type: "table", headers: ["", "虚拟机 VM", "容器 Container"], rows: [
        ["隔离", "完整操作系统，隔离强", "共享主机内核，轻量"],
        ["体积/启动", "GB 级、启动慢(分钟)", "MB 级、启动快(秒)"],
        ["代表", "VMware、KVM", "Docker、Kubernetes"],
        ["适合", "跑不同OS、强隔离", "微服务、快速弹性部署"],
      ] },
      { type: "callout", variant: "info", title: "容器与 K8s", body: "容器把应用和依赖打包，到处一致运行；**Kubernetes(K8s)** 负责大规模编排容器(自动调度、扩缩容、自愈)。它是云原生时代的核心，听到“云原生”大多和容器+K8s 有关。" },
      { type: "h2", text: "云服务三模型" },
      { type: "table", headers: ["模型", "你管什么", "类比", "例子"], rows: [
        ["IaaS 基础设施即服务", "自己装系统和应用，租用虚拟机/存储/网络", "租毛坯房", "云服务器 ECS/EC2"],
        ["PaaS 平台即服务", "只管应用和数据，平台搞定运行环境", "租精装房", "数据库服务、应用平台"],
        ["SaaS 软件即服务", "直接用现成软件", "住酒店", "企业邮箱、在线文档"],
      ] },
      { type: "h2", text: "云的部署模型" },
      { type: "list", items: [
        "**公有云**：用云厂商的共享资源（阿里云、AWS…），按需付费；",
        "**私有云**：企业自建专用云，可控性强；",
        "**混合云**：公有+私有结合，兼顾弹性与可控。",
      ] },
      { type: "callout", variant: "key", title: "回到起点", body: "第 1 部分说过“云=租用数据中心资源”。现在你懂了：虚拟化让一台机器变多台、容器让应用轻量弹性、云用三种模型把这些资源卖出去——而它们全都跑在你这门课学的数据中心里。" },
    ],
    quiz: [
      { id: "5-27-q1", kind: "single", question: "数据中心主流的 Hypervisor 类型是？",
        options: ["Type 2(装在OS上)", "Type 1(裸金属,直接装硬件)", "都不是", "只有家用"], answer: [1],
        explanation: "Type 1 裸金属(ESXi/KVM)性能好，是数据中心主流。" },
      { id: "5-27-q2", kind: "single", question: "容器相比虚拟机的特点是？",
        options: ["更重、启动更慢", "共享主机内核，轻量、启动快", "必须不同OS", "无法编排"], answer: [1],
        explanation: "容器共享内核、体积小、秒级启动，适合微服务弹性部署。" },
      { id: "5-27-q3", kind: "single", question: "租用云服务器自己装系统和应用，属于？",
        options: ["IaaS", "PaaS", "SaaS", "都不是"], answer: [0],
        explanation: "IaaS 提供基础设施(虚拟机/存储/网络)，用户自管系统与应用。" },
      { id: "5-27-q4", kind: "single", question: "Kubernetes(K8s) 的作用是？",
        options: ["制冷", "大规模编排容器(调度/扩缩容/自愈)", "供电", "存储备份"], answer: [1],
        explanation: "K8s 负责容器编排，是云原生时代的核心平台。" },
    ],
    flashcards: [
      { id: "5-27-f1", front: "虚拟化与Hypervisor", back: "软件把一台物理机分成多台VM；Type1裸金属(主流)/Type2装在OS上。", chapterId: "5-27" },
      { id: "5-27-f2", front: "VM vs 容器", back: "VM完整OS强隔离、重;容器共享内核、轻量秒启(Docker/K8s)。", chapterId: "5-27" },
      { id: "5-27-f3", front: "IaaS/PaaS/SaaS", back: "毛坯房/精装房/住酒店：管得越来越少。", chapterId: "5-27" },
      { id: "5-27-f4", front: "云部署模型", back: "公有云、私有云、混合云。", chapterId: "5-27" },
    ],
  },
];
